-- Card Naming System: Populate card_prefix and card_suffix for all 441 cards
-- Source: eAthena cardprefixnametable.txt + cardpostfixnametable.txt
-- PREFIX cards: text goes BEFORE item name (e.g., "Bloody Blade")
-- SUFFIX cards: text goes AFTER item name (e.g., "Blade of Counter")
-- Date: 2026-03-13

BEGIN;

UPDATE items SET card_prefix = 'Lucky', card_suffix = NULL WHERE item_id = 4001;
UPDATE items SET card_prefix = 'Vital', card_suffix = NULL WHERE item_id = 4002;
UPDATE items SET card_prefix = 'Hard', card_suffix = NULL WHERE item_id = 4003;
UPDATE items SET card_prefix = 'Dexterous', card_suffix = NULL WHERE item_id = 4004;
UPDATE items SET card_prefix = 'Hallowed', card_suffix = NULL WHERE item_id = 4005;
UPDATE items SET card_prefix = 'Lucky', card_suffix = NULL WHERE item_id = 4006;
UPDATE items SET card_prefix = 'Beholder', card_suffix = NULL WHERE item_id = 4007;
UPDATE items SET card_prefix = 'Extra', card_suffix = NULL WHERE item_id = 4008;
UPDATE items SET card_prefix = 'Light', card_suffix = NULL WHERE item_id = 4009;
UPDATE items SET card_prefix = 'Wise', card_suffix = NULL WHERE item_id = 4010;
UPDATE items SET card_prefix = 'Dynamic', card_suffix = NULL WHERE item_id = 4011;
UPDATE items SET card_prefix = 'Rigid', card_suffix = NULL WHERE item_id = 4012;
UPDATE items SET card_prefix = 'Excellent', card_suffix = NULL WHERE item_id = 4013;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Champion' WHERE item_id = 4014;
UPDATE items SET card_prefix = 'Quick', card_suffix = NULL WHERE item_id = 4015;
UPDATE items SET card_prefix = 'Speedy', card_suffix = NULL WHERE item_id = 4016;
UPDATE items SET card_prefix = 'Stun', card_suffix = NULL WHERE item_id = 4017;
UPDATE items SET card_prefix = 'Smart', card_suffix = NULL WHERE item_id = 4018;
UPDATE items SET card_prefix = 'Martyr', card_suffix = NULL WHERE item_id = 4019;
UPDATE items SET card_prefix = 'Blink', card_suffix = NULL WHERE item_id = 4020;
UPDATE items SET card_prefix = 'Skillful', card_suffix = NULL WHERE item_id = 4021;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Spore' WHERE item_id = 4022;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Desert' WHERE item_id = 4023;
UPDATE items SET card_prefix = 'Drowsy', card_suffix = NULL WHERE item_id = 4024;
UPDATE items SET card_prefix = 'Keen', card_suffix = NULL WHERE item_id = 4025;
UPDATE items SET card_prefix = 'Shrewd', card_suffix = NULL WHERE item_id = 4026;
UPDATE items SET card_prefix = 'Athletic', card_suffix = NULL WHERE item_id = 4027;
UPDATE items SET card_prefix = 'Double-forced', card_suffix = NULL WHERE item_id = 4028;
UPDATE items SET card_prefix = 'Wolverine', card_suffix = NULL WHERE item_id = 4029;
UPDATE items SET card_prefix = 'Windy', card_suffix = NULL WHERE item_id = 4030;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Ares' WHERE item_id = 4031;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Athena' WHERE item_id = 4032;
UPDATE items SET card_prefix = 'Detoxication', card_suffix = NULL WHERE item_id = 4033;
UPDATE items SET card_prefix = 'Clever', card_suffix = NULL WHERE item_id = 4034;
UPDATE items SET card_prefix = 'Bloody', card_suffix = NULL WHERE item_id = 4035;
UPDATE items SET card_prefix = 'Robust', card_suffix = NULL WHERE item_id = 4036;
UPDATE items SET card_prefix = 'Untouchable', card_suffix = NULL WHERE item_id = 4037;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Health' WHERE item_id = 4038;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Aristotle' WHERE item_id = 4039;
UPDATE items SET card_prefix = 'Teleport', card_suffix = NULL WHERE item_id = 4040;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Sandman' WHERE item_id = 4041;
UPDATE items SET card_prefix = NULL, card_suffix = 'of He-Man' WHERE item_id = 4042;
UPDATE items SET card_prefix = 'Hurricane', card_suffix = NULL WHERE item_id = 4043;
UPDATE items SET card_prefix = 'Hiding', card_suffix = NULL WHERE item_id = 4044;
UPDATE items SET card_prefix = 'Heavy', card_suffix = NULL WHERE item_id = 4045;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Cleric' WHERE item_id = 4046;
UPDATE items SET card_prefix = 'Ghost', card_suffix = NULL WHERE item_id = 4047;
UPDATE items SET card_prefix = 'Poison', card_suffix = NULL WHERE item_id = 4048;
UPDATE items SET card_prefix = 'Flammable', card_suffix = NULL WHERE item_id = 4049;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Hermes' WHERE item_id = 4050;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Flash' WHERE item_id = 4051;
UPDATE items SET card_prefix = 'Erudite', card_suffix = NULL WHERE item_id = 4052;
UPDATE items SET card_prefix = 'Healing', card_suffix = NULL WHERE item_id = 4053;
UPDATE items SET card_prefix = 'Holy', card_suffix = NULL WHERE item_id = 4054;
UPDATE items SET card_prefix = 'Ice', card_suffix = NULL WHERE item_id = 4055;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Warmth' WHERE item_id = 4056;
UPDATE items SET card_prefix = 'Silence', card_suffix = NULL WHERE item_id = 4057;
UPDATE items SET card_prefix = 'Cranial', card_suffix = NULL WHERE item_id = 4058;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Cadi' WHERE item_id = 4059;
UPDATE items SET card_prefix = 'Clamorous', card_suffix = NULL WHERE item_id = 4060;
UPDATE items SET card_prefix = 'Immortal', card_suffix = NULL WHERE item_id = 4061;
UPDATE items SET card_prefix = 'Envenom', card_suffix = NULL WHERE item_id = 4062;
UPDATE items SET card_prefix = 'Insecticide', card_suffix = NULL WHERE item_id = 4063;
UPDATE items SET card_prefix = 'Nimble', card_suffix = NULL WHERE item_id = 4064;
UPDATE items SET card_prefix = 'Underneath', card_suffix = NULL WHERE item_id = 4065;
UPDATE items SET card_prefix = 'Brutal', card_suffix = NULL WHERE item_id = 4066;
UPDATE items SET card_prefix = 'Atomic', card_suffix = NULL WHERE item_id = 4067;
UPDATE items SET card_prefix = 'Chemical', card_suffix = NULL WHERE item_id = 4068;
UPDATE items SET card_prefix = 'Saharic', card_suffix = NULL WHERE item_id = 4069;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Witch' WHERE item_id = 4070;
UPDATE items SET card_prefix = 'Angelic', card_suffix = NULL WHERE item_id = 4071;
UPDATE items SET card_prefix = 'Solid', card_suffix = NULL WHERE item_id = 4072;
UPDATE items SET card_prefix = 'Discount', card_suffix = NULL WHERE item_id = 4073;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Gargantua' WHERE item_id = 4074;
UPDATE items SET card_prefix = 'Hypnotic', card_suffix = NULL WHERE item_id = 4075;
UPDATE items SET card_prefix = 'Cursing', card_suffix = NULL WHERE item_id = 4076;
UPDATE items SET card_prefix = NULL, card_suffix = 'Under a Cast' WHERE item_id = 4077;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Recovery' WHERE item_id = 4078;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Muscle' WHERE item_id = 4079;
UPDATE items SET card_prefix = 'Fisher', card_suffix = NULL WHERE item_id = 4080;
UPDATE items SET card_prefix = 'Glorious', card_suffix = NULL WHERE item_id = 4081;
UPDATE items SET card_prefix = 'Gigantic', card_suffix = NULL WHERE item_id = 4082;
UPDATE items SET card_prefix = 'Homer''s', card_suffix = NULL WHERE item_id = 4083;
UPDATE items SET card_prefix = 'Blast', card_suffix = NULL WHERE item_id = 4084;
UPDATE items SET card_prefix = 'Damned', card_suffix = NULL WHERE item_id = 4085;
UPDATE items SET card_prefix = 'Critical', card_suffix = NULL WHERE item_id = 4086;
UPDATE items SET card_prefix = 'Order', card_suffix = NULL WHERE item_id = 4087;
UPDATE items SET card_prefix = 'Guard', card_suffix = NULL WHERE item_id = 4088;
UPDATE items SET card_prefix = 'Aqua', card_suffix = NULL WHERE item_id = 4089;
UPDATE items SET card_prefix = 'Amulet', card_suffix = NULL WHERE item_id = 4090;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Counter' WHERE item_id = 4091;
UPDATE items SET card_prefix = 'Boned', card_suffix = NULL WHERE item_id = 4092;
UPDATE items SET card_prefix = 'Cure', card_suffix = NULL WHERE item_id = 4093;
UPDATE items SET card_prefix = 'Kingbird', card_suffix = NULL WHERE item_id = 4094;
UPDATE items SET card_prefix = 'Genie''s', card_suffix = NULL WHERE item_id = 4095;
UPDATE items SET card_prefix = 'Venomer''s', card_suffix = NULL WHERE item_id = 4096;
UPDATE items SET card_prefix = 'Green', card_suffix = NULL WHERE item_id = 4097;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Zephyrus' WHERE item_id = 4098;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Ifrit' WHERE item_id = 4099;
UPDATE items SET card_prefix = 'Soul-Enchanted', card_suffix = NULL WHERE item_id = 4100;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Gnome' WHERE item_id = 4101;
UPDATE items SET card_prefix = 'Mocking', card_suffix = NULL WHERE item_id = 4102;
UPDATE items SET card_prefix = 'Clairvoyant', card_suffix = NULL WHERE item_id = 4103;
UPDATE items SET card_prefix = 'Chaos', card_suffix = NULL WHERE item_id = 4104;
UPDATE items SET card_prefix = 'Unfrozen', card_suffix = NULL WHERE item_id = 4105;
UPDATE items SET card_prefix = 'Ancient', card_suffix = NULL WHERE item_id = 4106;
UPDATE items SET card_prefix = 'Fledged', card_suffix = NULL WHERE item_id = 4107;
UPDATE items SET card_prefix = 'Innoxious', card_suffix = NULL WHERE item_id = 4108;
UPDATE items SET card_prefix = 'Flameguard', card_suffix = NULL WHERE item_id = 4109;
UPDATE items SET card_prefix = 'Viper''s', card_suffix = NULL WHERE item_id = 4110;
UPDATE items SET card_prefix = 'Decussate', card_suffix = NULL WHERE item_id = 4111;
UPDATE items SET card_prefix = 'Peerless', card_suffix = NULL WHERE item_id = 4112;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Ghost' WHERE item_id = 4113;
UPDATE items SET card_prefix = 'Poisoning', card_suffix = NULL WHERE item_id = 4114;
UPDATE items SET card_prefix = 'Malicious', card_suffix = NULL WHERE item_id = 4115;
UPDATE items SET card_prefix = 'Divine', card_suffix = NULL WHERE item_id = 4116;
UPDATE items SET card_prefix = 'Hybrid', card_suffix = NULL WHERE item_id = 4117;
UPDATE items SET card_prefix = 'Dragoon', card_suffix = NULL WHERE item_id = 4118;
UPDATE items SET card_prefix = 'Evil', card_suffix = NULL WHERE item_id = 4119;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Dragoon' WHERE item_id = 4120;
UPDATE items SET card_prefix = 'Perfect', card_suffix = NULL WHERE item_id = 4121;
UPDATE items SET card_prefix = 'Adurate', card_suffix = NULL WHERE item_id = 4122;
UPDATE items SET card_prefix = 'Bearer''s', card_suffix = NULL WHERE item_id = 4123;
UPDATE items SET card_prefix = 'Plasterer''s', card_suffix = NULL WHERE item_id = 4124;
UPDATE items SET card_prefix = 'Aqua', card_suffix = NULL WHERE item_id = 4125;
UPDATE items SET card_prefix = 'Titan', card_suffix = NULL WHERE item_id = 4126;
UPDATE items SET card_prefix = 'Insomniac', card_suffix = NULL WHERE item_id = 4127;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Deaf' WHERE item_id = 4128;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Rogue' WHERE item_id = 4129;
UPDATE items SET card_prefix = 'Divine', card_suffix = NULL WHERE item_id = 4130;
UPDATE items SET card_prefix = 'Hasty', card_suffix = NULL WHERE item_id = 4131;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Gemstone' WHERE item_id = 4132;
UPDATE items SET card_prefix = 'Immune', card_suffix = NULL WHERE item_id = 4133;
UPDATE items SET card_prefix = 'Spiritual', card_suffix = NULL WHERE item_id = 4134;
UPDATE items SET card_prefix = 'Mirror', card_suffix = NULL WHERE item_id = 4135;
UPDATE items SET card_prefix = NULL, card_suffix = 'from Hell' WHERE item_id = 4136;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Infinity' WHERE item_id = 4137;
UPDATE items SET card_prefix = 'Satanic', card_suffix = NULL WHERE item_id = 4138;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Moonlight' WHERE item_id = 4139;
UPDATE items SET card_prefix = 'Liberation', card_suffix = NULL WHERE item_id = 4140;
UPDATE items SET card_prefix = 'Deadly', card_suffix = NULL WHERE item_id = 4141;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Berserk' WHERE item_id = 4142;
UPDATE items SET card_prefix = 'Neutral', card_suffix = NULL WHERE item_id = 4143;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Eternity' WHERE item_id = 4144;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Bigmouth' WHERE item_id = 4145;
UPDATE items SET card_prefix = 'Reflect', card_suffix = NULL WHERE item_id = 4146;
UPDATE items SET card_prefix = 'Scythe-like', card_suffix = NULL WHERE item_id = 4147;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Kirin' WHERE item_id = 4148;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Serenity' WHERE item_id = 4149;
UPDATE items SET card_prefix = 'Spell-Proof', card_suffix = NULL WHERE item_id = 4150;
UPDATE items SET card_prefix = 'Havoc Bringer''s', card_suffix = NULL WHERE item_id = 4151;
UPDATE items SET card_prefix = 'Sprightly', card_suffix = NULL WHERE item_id = 4152;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Cancer' WHERE item_id = 4153;
UPDATE items SET card_prefix = 'Sweet Scented', card_suffix = NULL WHERE item_id = 4154;
UPDATE items SET card_prefix = 'Deadly Goblin''s', card_suffix = NULL WHERE item_id = 4155;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Fatal Flame' WHERE item_id = 4156;
UPDATE items SET card_prefix = 'Piercing', card_suffix = NULL WHERE item_id = 4157;
UPDATE items SET card_prefix = 'Slaughter', card_suffix = NULL WHERE item_id = 4158;
UPDATE items SET card_prefix = 'Deluxe', card_suffix = NULL WHERE item_id = 4159;
UPDATE items SET card_prefix = 'Superior', card_suffix = NULL WHERE item_id = 4160;
UPDATE items SET card_prefix = 'Anti-Magic', card_suffix = NULL WHERE item_id = 4161;
UPDATE items SET card_prefix = 'Sightless', card_suffix = NULL WHERE item_id = 4162;
UPDATE items SET card_prefix = 'Wild', card_suffix = NULL WHERE item_id = 4163;
UPDATE items SET card_prefix = 'Fisherman''s', card_suffix = NULL WHERE item_id = 4164;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Insect Soul Eater' WHERE item_id = 4165;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Jinx' WHERE item_id = 4166;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Beast Soul Eater' WHERE item_id = 4167;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Doom' WHERE item_id = 4168;
UPDATE items SET card_prefix = 'Spell Master''s', card_suffix = NULL WHERE item_id = 4169;
UPDATE items SET card_prefix = 'Solidifying', card_suffix = NULL WHERE item_id = 4170;
UPDATE items SET card_prefix = 'Soul Draining', card_suffix = NULL WHERE item_id = 4171;
UPDATE items SET card_prefix = 'Slicing', card_suffix = NULL WHERE item_id = 4172;
UPDATE items SET card_prefix = 'Mesmerizing', card_suffix = NULL WHERE item_id = 4173;
UPDATE items SET card_prefix = 'Deviant', card_suffix = NULL WHERE item_id = 4174;
UPDATE items SET card_prefix = 'Shoving', card_suffix = NULL WHERE item_id = 4175;
UPDATE items SET card_prefix = 'Fatal Serpentine', card_suffix = NULL WHERE item_id = 4176;
UPDATE items SET card_prefix = 'Green Stone', card_suffix = NULL WHERE item_id = 4177;
UPDATE items SET card_prefix = 'Bow-Master''s', card_suffix = NULL WHERE item_id = 4178;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Highlight' WHERE item_id = 4179;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Dragon Soul Eater' WHERE item_id = 4180;
UPDATE items SET card_prefix = 'Soundless', card_suffix = NULL WHERE item_id = 4181;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Demon Soul Eater' WHERE item_id = 4182;
UPDATE items SET card_prefix = 'Werewolf', card_suffix = NULL WHERE item_id = 4183;
UPDATE items SET card_prefix = 'Crushing', card_suffix = NULL WHERE item_id = 4184;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Wisdom' WHERE item_id = 4185;
UPDATE items SET card_prefix = 'Strenuous', card_suffix = NULL WHERE item_id = 4186;
UPDATE items SET card_prefix = NULL, card_suffix = 'of the Spooky Night' WHERE item_id = 4187;
UPDATE items SET card_prefix = 'Red Stone', card_suffix = NULL WHERE item_id = 4188;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Misfortune' WHERE item_id = 4189;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Last Laugh' WHERE item_id = 4190;
UPDATE items SET card_prefix = NULL, card_suffix = 'of the Stix' WHERE item_id = 4191;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Fatal Pisces' WHERE item_id = 4192;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Patience' WHERE item_id = 4193;
UPDATE items SET card_prefix = 'Overpowering', card_suffix = NULL WHERE item_id = 4194;
UPDATE items SET card_prefix = 'Blue Stone', card_suffix = NULL WHERE item_id = 4195;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Jellopy' WHERE item_id = 4196;
UPDATE items SET card_prefix = 'Lucky Streak', card_suffix = NULL WHERE item_id = 4197;
UPDATE items SET card_prefix = NULL, card_suffix = 'of True Sight' WHERE item_id = 4198;
UPDATE items SET card_prefix = 'Dashing', card_suffix = NULL WHERE item_id = 4199;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Mystical Resistance' WHERE item_id = 4200;
UPDATE items SET card_prefix = 'Crippling', card_suffix = NULL WHERE item_id = 4201;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Exorcism' WHERE item_id = 4202;
UPDATE items SET card_prefix = 'Blazing', card_suffix = NULL WHERE item_id = 4203;
UPDATE items SET card_prefix = 'Poacher''s', card_suffix = NULL WHERE item_id = 4204;
UPDATE items SET card_prefix = 'Blue Cubic', card_suffix = NULL WHERE item_id = 4205;
UPDATE items SET card_prefix = 'Cubic', card_suffix = NULL WHERE item_id = 4206;
UPDATE items SET card_prefix = 'Anti-Small', card_suffix = NULL WHERE item_id = 4207;
UPDATE items SET card_prefix = 'Energetic', card_suffix = NULL WHERE item_id = 4208;
UPDATE items SET card_prefix = 'Fiddler''s', card_suffix = NULL WHERE item_id = 4209;
UPDATE items SET card_prefix = 'Pressure', card_suffix = NULL WHERE item_id = 4210;
UPDATE items SET card_prefix = 'Virtuoso''s', card_suffix = NULL WHERE item_id = 4211;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Knock-Back' WHERE item_id = 4212;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Reticence' WHERE item_id = 4213;
UPDATE items SET card_prefix = 'Man-Eater''s', card_suffix = NULL WHERE item_id = 4214;
UPDATE items SET card_prefix = 'Rationing', card_suffix = NULL WHERE item_id = 4215;
UPDATE items SET card_prefix = 'Freezing', card_suffix = NULL WHERE item_id = 4216;
UPDATE items SET card_prefix = 'Rejuvenating', card_suffix = NULL WHERE item_id = 4217;
UPDATE items SET card_prefix = 'Nightmarish', card_suffix = NULL WHERE item_id = 4218;
UPDATE items SET card_prefix = 'Magic Stone', card_suffix = NULL WHERE item_id = 4219;
UPDATE items SET card_prefix = 'Faithful', card_suffix = NULL WHERE item_id = 4220;
UPDATE items SET card_prefix = 'Insect Collector''s', card_suffix = NULL WHERE item_id = 4221;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Sleep' WHERE item_id = 4222;
UPDATE items SET card_prefix = 'Stun-Proof', card_suffix = NULL WHERE item_id = 4223;
UPDATE items SET card_prefix = 'Monsoon', card_suffix = NULL WHERE item_id = 4224;
UPDATE items SET card_prefix = 'Slingshot', card_suffix = NULL WHERE item_id = 4225;
UPDATE items SET card_prefix = 'Supreme', card_suffix = NULL WHERE item_id = 4226;
UPDATE items SET card_prefix = 'Roast Scented', card_suffix = NULL WHERE item_id = 4227;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Siesta' WHERE item_id = 4228;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Torment' WHERE item_id = 4229;
UPDATE items SET card_prefix = 'Coward''s', card_suffix = NULL WHERE item_id = 4230;
UPDATE items SET card_prefix = 'Charging', card_suffix = NULL WHERE item_id = 4231;
UPDATE items SET card_prefix = 'Refreshing', card_suffix = NULL WHERE item_id = 4232;
UPDATE items SET card_prefix = 'Lucky Fluke', card_suffix = NULL WHERE item_id = 4233;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Clarity' WHERE item_id = 4234;
UPDATE items SET card_prefix = 'Fallen Angel''s', card_suffix = NULL WHERE item_id = 4235;
UPDATE items SET card_prefix = 'Protective', card_suffix = NULL WHERE item_id = 4236;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Godly Wrath' WHERE item_id = 4237;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Doubled Power' WHERE item_id = 4238;
UPDATE items SET card_prefix = 'Veteran Hunter''s', card_suffix = NULL WHERE item_id = 4239;
UPDATE items SET card_prefix = 'Magic-Proof', card_suffix = NULL WHERE item_id = 4240;
UPDATE items SET card_prefix = 'Miraculous', card_suffix = NULL WHERE item_id = 4241;
UPDATE items SET card_prefix = 'Prime', card_suffix = NULL WHERE item_id = 4242;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Escape' WHERE item_id = 4243;
UPDATE items SET card_prefix = 'Seeker''s', card_suffix = NULL WHERE item_id = 4244;
UPDATE items SET card_prefix = 'Assassinator''s', card_suffix = NULL WHERE item_id = 4245;
UPDATE items SET card_prefix = 'Killing', card_suffix = NULL WHERE item_id = 4246;
UPDATE items SET card_prefix = 'Starfish''s', card_suffix = NULL WHERE item_id = 4247;
UPDATE items SET card_prefix = 'Shining Cross', card_suffix = NULL WHERE item_id = 4248;
UPDATE items SET card_prefix = 'Witch Doctor''s', card_suffix = NULL WHERE item_id = 4249;
UPDATE items SET card_prefix = 'Anti-Large', card_suffix = NULL WHERE item_id = 4250;
UPDATE items SET card_prefix = 'Invasion', card_suffix = NULL WHERE item_id = 4251;
UPDATE items SET card_prefix = 'Four Leaf Clover', card_suffix = NULL WHERE item_id = 4252;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Royal Guard' WHERE item_id = 4253;
UPDATE items SET card_prefix = 'Anti-Medium', card_suffix = NULL WHERE item_id = 4254;
UPDATE items SET card_prefix = 'Smashing', card_suffix = NULL WHERE item_id = 4255;
UPDATE items SET card_prefix = 'Desirable', card_suffix = NULL WHERE item_id = 4256;
UPDATE items SET card_prefix = 'Wing', card_suffix = NULL WHERE item_id = 4257;
UPDATE items SET card_prefix = 'Prodigy', card_suffix = NULL WHERE item_id = 4258;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Nature' WHERE item_id = 4259;
UPDATE items SET card_prefix = 'Confusion Resistant', card_suffix = NULL WHERE item_id = 4260;
UPDATE items SET card_prefix = 'Bleed Resistant', card_suffix = NULL WHERE item_id = 4261;
UPDATE items SET card_prefix = 'Dark Sky', card_suffix = NULL WHERE item_id = 4262;
UPDATE items SET card_prefix = 'Bloodlust', card_suffix = NULL WHERE item_id = 4263;
UPDATE items SET card_prefix = 'Thunderbolt', card_suffix = NULL WHERE item_id = 4264;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Dawn' WHERE item_id = 4265;
UPDATE items SET card_prefix = 'Magic Resistant', card_suffix = NULL WHERE item_id = 4266;
UPDATE items SET card_prefix = 'Dragon Slayer''s', card_suffix = NULL WHERE item_id = 4267;
UPDATE items SET card_prefix = 'Extending', card_suffix = NULL WHERE item_id = 4268;
UPDATE items SET card_prefix = 'Fatasm', card_suffix = NULL WHERE item_id = 4269;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Venom' WHERE item_id = 4270;
UPDATE items SET card_prefix = 'Yellow Stone', card_suffix = NULL WHERE item_id = 4271;
UPDATE items SET card_prefix = 'Swift', card_suffix = NULL WHERE item_id = 4272;
UPDATE items SET card_prefix = 'Shell', card_suffix = NULL WHERE item_id = 4273;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Undead Soul Eater' WHERE item_id = 4274;
UPDATE items SET card_prefix = 'Undead Killer''s', card_suffix = NULL WHERE item_id = 4275;
UPDATE items SET card_prefix = 'Crucial', card_suffix = NULL WHERE item_id = 4276;
UPDATE items SET card_prefix = 'Dominatrix', card_suffix = NULL WHERE item_id = 4277;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Magical Immunity' WHERE item_id = 4278;
UPDATE items SET card_prefix = 'Soul Collector''s', card_suffix = NULL WHERE item_id = 4279;
UPDATE items SET card_prefix = 'Blessed', card_suffix = NULL WHERE item_id = 4280;
UPDATE items SET card_prefix = 'Diligent', card_suffix = NULL WHERE item_id = 4281;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Reservoir' WHERE item_id = 4282;
UPDATE items SET card_prefix = 'Mana Sphere', card_suffix = NULL WHERE item_id = 4283;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Caress' WHERE item_id = 4284;
UPDATE items SET card_prefix = 'Elven-Enchanted', card_suffix = NULL WHERE item_id = 4285;
UPDATE items SET card_prefix = 'Terrorizing', card_suffix = NULL WHERE item_id = 4286;
UPDATE items SET card_prefix = 'Magically Shielded', card_suffix = NULL WHERE item_id = 4287;
UPDATE items SET card_prefix = 'Maestro', card_suffix = NULL WHERE item_id = 4288;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Plant Soul Eater' WHERE item_id = 4289;
UPDATE items SET card_prefix = 'Mirror', card_suffix = NULL WHERE item_id = 4290;
UPDATE items SET card_prefix = 'Deadly Kobold''s', card_suffix = NULL WHERE item_id = 4291;
UPDATE items SET card_prefix = 'Deadly Plant''s', card_suffix = NULL WHERE item_id = 4292;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Chance' WHERE item_id = 4293;
UPDATE items SET card_prefix = 'Sneaky', card_suffix = NULL WHERE item_id = 4294;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Blackout' WHERE item_id = 4295;
UPDATE items SET card_prefix = 'Greedy', card_suffix = NULL WHERE item_id = 4296;
UPDATE items SET card_prefix = 'Poaching', card_suffix = NULL WHERE item_id = 4297;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Mayhem' WHERE item_id = 4298;
UPDATE items SET card_prefix = 'Guardian''s', card_suffix = NULL WHERE item_id = 4299;
UPDATE items SET card_prefix = 'Venomous Charge', card_suffix = NULL WHERE item_id = 4300;
UPDATE items SET card_prefix = 'Traumatic', card_suffix = NULL WHERE item_id = 4301;
UPDATE items SET card_prefix = 'High Risk', card_suffix = NULL WHERE item_id = 4302;
UPDATE items SET card_prefix = 'Mystic', card_suffix = NULL WHERE item_id = 4303;
UPDATE items SET card_prefix = 'Shield Master''s', card_suffix = NULL WHERE item_id = 4304;
UPDATE items SET card_prefix = 'Explosive', card_suffix = NULL WHERE item_id = 4305;
UPDATE items SET card_prefix = 'King''s', card_suffix = NULL WHERE item_id = 4306;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Marine Soul Eater' WHERE item_id = 4307;
UPDATE items SET card_prefix = 'Power Draining', card_suffix = NULL WHERE item_id = 4308;
UPDATE items SET card_prefix = 'Reinforced', card_suffix = NULL WHERE item_id = 4309;
UPDATE items SET card_prefix = 'Fatally Evil', card_suffix = NULL WHERE item_id = 4310;
UPDATE items SET card_prefix = 'Anti-Evil', card_suffix = NULL WHERE item_id = 4311;
UPDATE items SET card_prefix = NULL, card_suffix = 'of the Soul' WHERE item_id = 4312;
UPDATE items SET card_prefix = 'Bogie', card_suffix = NULL WHERE item_id = 4313;
UPDATE items SET card_prefix = 'Fire-Proof', card_suffix = NULL WHERE item_id = 4314;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Stone Curse' WHERE item_id = 4315;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Angel Soul Eater' WHERE item_id = 4316;
UPDATE items SET card_prefix = 'Aural', card_suffix = NULL WHERE item_id = 4317;
UPDATE items SET card_prefix = 'Storm-Bringer''s', card_suffix = NULL WHERE item_id = 4318;
UPDATE items SET card_prefix = 'Sword-Master''s', card_suffix = NULL WHERE item_id = 4319;
UPDATE items SET card_prefix = 'Meteoric', card_suffix = NULL WHERE item_id = 4320;
UPDATE items SET card_prefix = 'Polymorphic', card_suffix = NULL WHERE item_id = 4321;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Retaliation' WHERE item_id = 4322;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Frost' WHERE item_id = 4323;
UPDATE items SET card_prefix = 'Arctic', card_suffix = NULL WHERE item_id = 4324;
UPDATE items SET card_prefix = 'Vicious', card_suffix = NULL WHERE item_id = 4325;
UPDATE items SET card_prefix = 'Ocean Scented', card_suffix = NULL WHERE item_id = 4326;
UPDATE items SET card_prefix = 'Spell Flow', card_suffix = NULL WHERE item_id = 4327;
UPDATE items SET card_prefix = 'Hyper', card_suffix = NULL WHERE item_id = 4328;
UPDATE items SET card_prefix = 'Soul Gain', card_suffix = NULL WHERE item_id = 4329;
UPDATE items SET card_prefix = 'Curse Lift', card_suffix = NULL WHERE item_id = 4330;
UPDATE items SET card_prefix = 'Evasion', card_suffix = NULL WHERE item_id = 4331;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Talent' WHERE item_id = 4332;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Chaotic Venom' WHERE item_id = 4333;
UPDATE items SET card_prefix = 'Anti-Sniping', card_suffix = NULL WHERE item_id = 4334;
UPDATE items SET card_prefix = 'Gnome', card_suffix = NULL WHERE item_id = 4335;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Vitality' WHERE item_id = 4336;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Wildcat' WHERE item_id = 4337;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Vital Switching' WHERE item_id = 4338;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Stone Wall' WHERE item_id = 4339;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Requiem' WHERE item_id = 4340;
UPDATE items SET card_prefix = 'Disarm', card_suffix = NULL WHERE item_id = 4341;
UPDATE items SET card_prefix = 'Mammoth', card_suffix = NULL WHERE item_id = 4342;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Creator' WHERE item_id = 4343;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Value' WHERE item_id = 4344;
UPDATE items SET card_prefix = 'Sylph', card_suffix = NULL WHERE item_id = 4345;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Power Switching' WHERE item_id = 4346;
UPDATE items SET card_prefix = 'Stamina', card_suffix = NULL WHERE item_id = 4347;
UPDATE items SET card_prefix = 'Gangster', card_suffix = NULL WHERE item_id = 4348;
UPDATE items SET card_prefix = 'Anti-Arrow', card_suffix = NULL WHERE item_id = 4349;
UPDATE items SET card_prefix = 'Undine', card_suffix = NULL WHERE item_id = 4350;
UPDATE items SET card_prefix = 'Low Level', card_suffix = NULL WHERE item_id = 4351;
UPDATE items SET card_prefix = 'Undecided', card_suffix = NULL WHERE item_id = 4352;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Rejuvenation' WHERE item_id = 4353;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Stability' WHERE item_id = 4354;
UPDATE items SET card_prefix = 'Healthy', card_suffix = NULL WHERE item_id = 4355;
UPDATE items SET card_prefix = 'Magic Cancel', card_suffix = NULL WHERE item_id = 4356;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Fury' WHERE item_id = 4357;
UPDATE items SET card_prefix = 'Lost-Power', card_suffix = NULL WHERE item_id = 4358;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Shadow' WHERE item_id = 4359;
UPDATE items SET card_prefix = 'Assassin', card_suffix = NULL WHERE item_id = 4360;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Hollgren' WHERE item_id = 4361;
UPDATE items SET card_prefix = 'Heat', card_suffix = NULL WHERE item_id = 4362;
UPDATE items SET card_prefix = 'Protection', card_suffix = NULL WHERE item_id = 4363;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Magic Sealing' WHERE item_id = 4364;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Tempest' WHERE item_id = 4365;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Caster' WHERE item_id = 4366;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Squeezing' WHERE item_id = 4367;
UPDATE items SET card_prefix = 'Rapid', card_suffix = NULL WHERE item_id = 4368;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Luck Switching' WHERE item_id = 4369;
UPDATE items SET card_prefix = 'Weakening', card_suffix = NULL WHERE item_id = 4370;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Paladin' WHERE item_id = 4371;
UPDATE items SET card_prefix = 'Undecided', card_suffix = NULL WHERE item_id = 4372;
UPDATE items SET card_prefix = 'Cursed', card_suffix = NULL WHERE item_id = 4373;
UPDATE items SET card_prefix = 'Undecided', card_suffix = NULL WHERE item_id = 4374;
UPDATE items SET card_prefix = 'Extra High Level', card_suffix = NULL WHERE item_id = 4375;
UPDATE items SET card_prefix = 'Manful', card_suffix = NULL WHERE item_id = 4376;
UPDATE items SET card_prefix = 'Sweetie', card_suffix = NULL WHERE item_id = 4377;
UPDATE items SET card_prefix = 'Low Level', card_suffix = NULL WHERE item_id = 4378;
UPDATE items SET card_prefix = 'Low Level', card_suffix = NULL WHERE item_id = 4379;
UPDATE items SET card_prefix = 'Salamander', card_suffix = NULL WHERE item_id = 4380;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Wanderer' WHERE item_id = 4381;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Scholar' WHERE item_id = 4382;
UPDATE items SET card_prefix = 'Chaotic', card_suffix = NULL WHERE item_id = 4383;
UPDATE items SET card_prefix = 'Magic Eater', card_suffix = NULL WHERE item_id = 4384;
UPDATE items SET card_prefix = 'Drink', card_suffix = NULL WHERE item_id = 4385;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Magic Shelter' WHERE item_id = 4386;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Agility Switching' WHERE item_id = 4387;
UPDATE items SET card_prefix = 'Soul', card_suffix = NULL WHERE item_id = 4388;
UPDATE items SET card_prefix = 'Elemental', card_suffix = NULL WHERE item_id = 4389;
UPDATE items SET card_prefix = 'Blooding', card_suffix = NULL WHERE item_id = 4390;
UPDATE items SET card_prefix = 'Snack', card_suffix = NULL WHERE item_id = 4391;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Dexterity Switching' WHERE item_id = 4392;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Intelligence Switching' WHERE item_id = 4393;
UPDATE items SET card_prefix = 'Divine Cross', card_suffix = NULL WHERE item_id = 4394;
UPDATE items SET card_prefix = 'Slug', card_suffix = NULL WHERE item_id = 4395;
UPDATE items SET card_prefix = 'Dull', card_suffix = NULL WHERE item_id = 4396;
UPDATE items SET card_prefix = 'Stupidity', card_suffix = NULL WHERE item_id = 4397;
UPDATE items SET card_prefix = 'Darkness', card_suffix = NULL WHERE item_id = 4398;
UPDATE items SET card_prefix = 'Penetration', card_suffix = NULL WHERE item_id = 4399;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Temptation' WHERE item_id = 4400;
UPDATE items SET card_prefix = 'Swift', card_suffix = NULL WHERE item_id = 4401;
UPDATE items SET card_prefix = 'Strange', card_suffix = NULL WHERE item_id = 4402;
UPDATE items SET card_prefix = 'Undecided', card_suffix = NULL WHERE item_id = 4403;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Chaotic Bleeding' WHERE item_id = 4404;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Magic Mirror' WHERE item_id = 4405;
UPDATE items SET card_prefix = 'Twinkle', card_suffix = NULL WHERE item_id = 4406;
UPDATE items SET card_prefix = NULL, card_suffix = 'of Elimination' WHERE item_id = 4407;
UPDATE items SET card_prefix = 'Abyss', card_suffix = NULL WHERE item_id = 4408;
UPDATE items SET card_prefix = 'Panic', card_suffix = NULL WHERE item_id = 4409;
UPDATE items SET card_prefix = 'Madness', card_suffix = NULL WHERE item_id = 4410;
UPDATE items SET card_prefix = 'Shrewd', card_suffix = NULL WHERE item_id = 4411;
UPDATE items SET card_prefix = 'Aria', card_suffix = NULL WHERE item_id = 4412;
UPDATE items SET card_prefix = 'Resistance', card_suffix = NULL WHERE item_id = 4413;
UPDATE items SET card_prefix = 'Gorgon', card_suffix = NULL WHERE item_id = 4414;
UPDATE items SET card_prefix = 'Sweet', card_suffix = NULL WHERE item_id = 4415;
UPDATE items SET card_prefix = 'Grain', card_suffix = NULL WHERE item_id = 4416;
UPDATE items SET card_prefix = 'Flow', card_suffix = NULL WHERE item_id = 4417;
UPDATE items SET card_prefix = 'Hailing', card_suffix = NULL WHERE item_id = 4418;
UPDATE items SET card_prefix = 'Jack Frost', card_suffix = NULL WHERE item_id = 4419;
UPDATE items SET card_prefix = 'Solace', card_suffix = NULL WHERE item_id = 4420;
UPDATE items SET card_prefix = 'Crane', card_suffix = NULL WHERE item_id = 4421;
UPDATE items SET card_prefix = 'Breeze', card_suffix = NULL WHERE item_id = 4422;
UPDATE items SET card_prefix = 'Spread', card_suffix = NULL WHERE item_id = 4423;
UPDATE items SET card_prefix = 'Stony', card_suffix = NULL WHERE item_id = 4424;
UPDATE items SET card_prefix = 'Beast', card_suffix = NULL WHERE item_id = 4425;
UPDATE items SET card_prefix = 'Exceed', card_suffix = NULL WHERE item_id = 4426;
UPDATE items SET card_prefix = 'Force', card_suffix = NULL WHERE item_id = 4427;
UPDATE items SET card_prefix = 'Shaft', card_suffix = NULL WHERE item_id = 4428;
UPDATE items SET card_prefix = 'Nessus', card_suffix = NULL WHERE item_id = 4429;
UPDATE items SET card_prefix = 'Inferno', card_suffix = NULL WHERE item_id = 4430;
UPDATE items SET card_prefix = 'Stygia', card_suffix = NULL WHERE item_id = 4431;
UPDATE items SET card_prefix = 'Scorching', card_suffix = NULL WHERE item_id = 4432;
UPDATE items SET card_prefix = 'Ignite', card_suffix = NULL WHERE item_id = 4433;
UPDATE items SET card_prefix = 'Miner''s', card_suffix = NULL WHERE item_id = 4434;
UPDATE items SET card_prefix = 'Violent', card_suffix = NULL WHERE item_id = 4435;
UPDATE items SET card_prefix = 'Lunatic', card_suffix = NULL WHERE item_id = 4436;
UPDATE items SET card_prefix = 'Mad Dog', card_suffix = NULL WHERE item_id = 4437;
UPDATE items SET card_prefix = 'Mental', card_suffix = NULL WHERE item_id = 4438;
UPDATE items SET card_prefix = 'Anathema', card_suffix = NULL WHERE item_id = 4439;
UPDATE items SET card_prefix = 'Ignore', card_suffix = NULL WHERE item_id = 4440;
UPDATE items SET card_prefix = 'Arrogant', card_suffix = NULL WHERE item_id = 4441;

COMMIT;

-- Summary: 327 prefix cards, 114 suffix cards, 441 total
