// Auto-generated by scripts/generate_canonical_migration.js
// Consumable item use-effect data parsed from rAthena scripts
// Generated: 2026-03-11T18:30:03.567Z
// Total effects: 490
//
// Effect types:
//   heal        — { hpMin, hpMax, spMin, spMax } fixed heal
//   percentheal — { hp, sp } percentage heal
//   cure        — { cures: [SC_...] } remove status effects
//   itemskill   — { skill, level } trigger skill on use
//   sc_start    — { status, duration, value } apply status
//   multi       — { effects: [...] } multiple effects

const ITEM_USE_EFFECTS = {
    501: {"type":"heal","hpMin":45,"hpMax":65}, // Red Potion
    502: {"type":"heal","hpMin":105,"hpMax":145}, // Orange Potion
    503: {"type":"heal","hpMin":175,"hpMax":235}, // Yellow Potion
    504: {"type":"heal","hpMin":325,"hpMax":405}, // White Potion
    505: {"type":"heal","spMin":40,"spMax":60}, // Blue Potion
    506: {"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind"]}, // Green Potion
    507: {"type":"heal","hpMin":18,"hpMax":28}, // Red Herb
    508: {"type":"heal","hpMin":38,"hpMax":58}, // Yellow Herb
    509: {"type":"heal","hpMin":75,"hpMax":115}, // White Herb
    510: {"type":"heal","spMin":15,"spMax":30}, // Blue Herb
    511: {"type":"cure","cures":["SC_Poison"]}, // Green Herb
    512: {"type":"heal","hpMin":16,"hpMax":22}, // Apple
    513: {"type":"heal","hpMin":17,"hpMax":21}, // Banana
    514: {"type":"heal","spMin":10,"spMax":15}, // Grape
    515: {"type":"heal","hpMin":18,"hpMax":20}, // Carrot
    516: {"type":"heal","hpMin":15,"hpMax":23}, // Potato
    517: {"type":"heal","hpMin":70,"hpMax":100}, // Meat
    518: {"type":"heal","hpMin":70,"hpMax":100,"spMin":20,"spMax":40}, // Honey
    519: {"type":"heal","hpMin":27,"hpMax":37}, // Milk
    520: {"type":"heal","hpMin":175,"hpMax":235}, // Hinalle Leaflet
    521: {"type":"heal","hpMin":325,"hpMax":405}, // Aloe Leaflet
    522: {"type":"heal","hpMin":400,"hpMax":600}, // Mastela Fruit
    523: {"type":"cure","cures":["SC_Curse"]}, // Holy Water
    525: {"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}, // Panacea
    526: {"type":"multi","effects":[{"type":"heal","hpMin":325,"hpMax":405,"spMin":40,"spMax":60},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Royal Jelly
    528: {"type":"heal","hpMin":72,"hpMax":108}, // Monster's Feed
    529: {"type":"heal","hpMin":45,"hpMax":65}, // Candy
    530: {"type":"heal","hpMin":105,"hpMax":145}, // Candy Cane
    531: {"type":"heal","hpMin":25,"hpMax":35}, // Apple Juice
    532: {"type":"heal","hpMin":26,"hpMax":34}, // Banana Juice
    533: {"type":"heal","spMin":15,"spMax":25}, // Grape Juice
    534: {"type":"heal","hpMin":27,"hpMax":33}, // Carrot Juice
    535: {"type":"heal","hpMin":19,"hpMax":19}, // Pumpkin
    536: {"type":"heal","hpMin":105,"hpMax":145}, // Ice Cream
    537: {"type":"heal","hpMin":50,"hpMax":90}, // Pet Food
    538: {"type":"heal","hpMin":160,"hpMax":200}, // Well-baked Cookie
    539: {"type":"heal","hpMin":270,"hpMax":330}, // Piece of Cake
    540: {"type":"heal","hpMin":185,"hpMax":225}, // Falcon Food
    541: {"type":"heal","hpMin":325,"hpMax":405}, // PecoPeco Food
    544: {"type":"heal","hpMin":25,"hpMax":60}, // Raw Fish
    545: {"type":"heal","hpMin":45,"hpMax":65}, // Condensed Red Potion
    546: {"type":"heal","hpMin":175,"hpMax":235}, // Condensed Yellow Potion
    547: {"type":"heal","hpMin":325,"hpMax":405}, // Condensed White Potion
    548: {"type":"heal","spMin":10,"spMax":15}, // Cheese
    549: {"type":"heal","hpMin":50,"hpMax":100}, // Yam
    550: {"type":"heal","hpMin":10,"hpMax":15}, // Rice Cake
    551: {"type":"heal","hpMin":50,"hpMax":60}, // Sushi
    552: {"type":"heal","hpMin":70,"hpMax":90,"spMin":20,"spMax":30}, // Ketupat
    553: {"type":"heal","hpMin":35,"hpMax":70}, // Bao
    554: {"type":"multi","effects":[{"type":"heal","hpMin":105,"hpMax":145},{"type":"sc_start","status":"SC_Stun","duration":3000,"value":0}]}, // Mochi
    555: {"type":"heal","hpMin":105,"hpMax":145}, // Traditional Rice Cake
    556: {"type":"heal","hpMin":20,"hpMax":25}, // Rice Cake Stick
    557: {"type":"heal","hpMin":25,"hpMax":30}, // Neatly Sliced Rice Cake
    558: {"type":"heal","hpMin":1,"hpMax":1,"spMin":1,"spMax":1}, // Chocolate
    559: {"type":"heal","hpMin":50,"hpMax":50,"spMin":50,"spMax":50}, // Hand-made Chocolate
    560: {"type":"heal","hpMin":50,"hpMax":50,"spMin":50,"spMax":50}, // Handmade White Chocolate
    561: {"type":"heal","hpMin":50,"hpMax":50,"spMin":50,"spMax":50}, // White Chocolate
    562: {"type":"heal","hpMin":70,"hpMax":100}, // Doublecrust Swiss Fondue
    563: {"type":"heal","hpMin":375,"hpMax":445}, // Doublecrust Swiss Fondue
    564: {"type":"heal","hpMin":200,"hpMax":200}, // Rice Ball
    565: {"type":"heal","hpMin":142,"hpMax":274}, // Vita500
    566: {"type":"multi","effects":[{"type":"heal","hpMin":244,"hpMax":350,"spMin":10,"spMax":30},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Tom Yum Goong
    567: {"type":"heal","hpMin":117,"hpMax":192}, // Shrimp
    568: {"type":"heal","spMin":10,"spMax":20}, // Lemon
    569: {"type":"heal","hpMin":22,"hpMax":33}, // Novice Potion
    570: {"type":"heal","hpMin":45,"hpMax":65}, // Lucky Candy
    571: {"type":"heal","hpMin":105,"hpMax":145}, // Lucky Candy Cane
    572: {"type":"heal","hpMin":160,"hpMax":200}, // Lucky Cookie
    573: {"type":"multi","effects":[{"type":"heal","hpMin":330,"hpMax":410,"spMin":45,"spMax":65},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Chocolate Drink
    574: {"type":"heal","hpMin":33,"hpMax":42}, // Egg
    575: {"type":"heal","hpMin":270,"hpMax":330}, // 2nd Anniversary Cake
    576: {"type":"heal","hpMin":150,"hpMax":300,"spMin":20,"spMax":30}, // Prickly Fruit
    577: {"type":"heal","hpMin":60,"hpMax":70}, // Bag of Grain
    578: {"type":"heal","spMin":16,"spMax":28}, // Strawberry
    579: {"type":"heal","hpMin":100,"hpMax":150}, // Fresh Fish
    580: {"type":"heal","hpMin":50,"hpMax":90}, // Bread
    581: {"type":"heal","hpMin":20,"hpMax":30}, // Edible Mushroom
    582: {"type":"heal","hpMin":10,"hpMax":20,"spMin":10,"spMax":20}, // Orange
    583: {"type":"multi","effects":[{"type":"heal","hpMin":325,"hpMax":405,"spMin":40,"spMax":60},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Ketupat Sayur
    584: {"type":"heal","hpMin":40,"hpMax":70}, // Fish Cake Soup
    585: {"type":"multi","effects":[{"type":"heal","hpMin":15,"hpMax":20},{"type":"itemskill","skill":"PR_MAGNIFICAT","level":3}]}, // Brusti
    586: {"type":"heal","hpMin":325,"hpMax":405}, // Mother's Cake
    587: {"type":"heal","hpMin":270,"hpMax":330,"spMin":20,"spMax":30}, // Red Prickly Fruit
    588: {"type":"heal","hpMin":40,"hpMax":70}, // Spaghetti
    589: {"type":"heal","hpMin":375,"hpMax":445}, // Pizza
    590: {"type":"heal","hpMin":50,"hpMax":90}, // Pretzel
    591: {"type":"multi","effects":[{"type":"heal","hpMin":325,"hpMax":405,"spMin":40,"spMax":60},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Caviar Pancake
    592: {"type":"multi","effects":[{"type":"heal","hpMin":325,"hpMax":405,"spMin":40,"spMax":60},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Jam Pancake
    593: {"type":"multi","effects":[{"type":"heal","hpMin":325,"hpMax":405,"spMin":40,"spMax":60},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Honey Pancake
    594: {"type":"multi","effects":[{"type":"heal","hpMin":325,"hpMax":405,"spMin":40,"spMax":60},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Sour-Cream Pancake
    595: {"type":"multi","effects":[{"type":"heal","hpMin":325,"hpMax":405,"spMin":40,"spMax":60},{"type":"cure","cures":["SC_Poison","SC_Silence","SC_Blind","SC_Confusion","SC_Curse","SC_Hallucination"]}]}, // Mushroom Pancake
    596: {"type":"heal","spMin":1,"spMax":100}, // Cute Strawberry-Choco
    597: {"type":"heal","hpMin":10,"hpMax":400}, // Lovely Choco-Tart
    598: {"type":"heal","hpMin":45,"hpMax":65}, // Light Red Potion
    599: {"type":"heal","hpMin":105,"hpMax":145}, // Light Orange Potion
    601: {"type":"itemskill","skill":"AL_TELEPORT","level":1}, // Fly Wing
    602: {"type":"itemskill","skill":"AL_TELEPORT","level":3}, // Butterfly Wing
    605: {"type":"itemskill","skill":"SM_ENDURE","level":1}, // Anodyne
    606: {"type":"itemskill","skill":"SM_SELFPROVOKE","level":1}, // Aloevera
    607: {"type":"percentheal","hp":100,"sp":100}, // Yggdrasil Berry
    608: {"type":"percentheal","hp":50,"sp":50}, // Yggdrasil Seed
    610: {"type":"itemskill","skill":"ALL_RESURRECTION","level":1}, // Yggdrasil Leaf
    611: {"type":"itemskill","skill":"MC_IDENTIFY","level":1}, // Magnifier
    645: {"type":"sc_start","status":"SC_ASPDPOTION0","duration":1800000,"value":0}, // Concentration Potion
    656: {"type":"sc_start","status":"SC_ASPDPOTION1","duration":1800000,"value":0}, // Awakening Potion
    657: {"type":"sc_start","status":"SC_ASPDPOTION2","duration":1800000,"value":0}, // Berserk Potion
    662: {"type":"sc_start","status":"SC_SPEEDUP0","duration":180000,"value":25}, // Authoritative Badge
    663: {"type":"percentheal","hp":10,"sp":0}, // Korean Rice Cake
    669: {"type":"percentheal","hp":-100,"sp":-100}, // Tempting Rice-Cake Soup
    678: {"type":"multi","effects":[{"type":"percentheal","hp":-100,"sp":-100},{"type":"sc_start","status":"SC_DPoison","duration":60000,"value":0},{"type":"sc_start","status":"SC_ASPDPOTION3","duration":60000,"value":0}]}, // Poison Bottle
    679: {"type":"sc_start","status":"SC_Poison","duration":50000,"value":0}, // Pilule
    680: {"type":"percentheal","hp":0,"sp":20}, // Magic Carnation
    681: {"type":"sc_start","status":"SC_WEDDING","duration":600000,"value":0}, // Sweet Memory of Marriage
    682: {"type":"sc_start","status":"SC_ATKPOTION","duration":60000,"value":30}, // Distilled Fighting Spirit
    683: {"type":"sc_start","status":"SC_MATKPOTION","duration":60000,"value":30}, // Herb of Incantation
    684: {"type":"multi","effects":[{"type":"sc_start","status":"SC_ATKPOTION","duration":60000,"value":10},{"type":"sc_start","status":"SC_MATKPOTION","duration":60000,"value":10}]}, // Durian
    685: {"type":"percentheal","hp":100,"sp":50}, // Ramadan
    686: {"type":"itemskill","skill":"WZ_EARTHSPIKE","level":3}, // Level 3 Earth Spike
    687: {"type":"itemskill","skill":"WZ_EARTHSPIKE","level":5}, // Level 5 Earth Spike
    688: {"type":"itemskill","skill":"MG_COLDBOLT","level":3}, // Level 3 Cold Bolt
    689: {"type":"itemskill","skill":"MG_COLDBOLT","level":5}, // Level 5 Cold Bolt
    690: {"type":"itemskill","skill":"MG_FIREBOLT","level":3}, // Level 3 Fire Bolt
    691: {"type":"itemskill","skill":"MG_FIREBOLT","level":5}, // Level 5 Fire Bolt
    692: {"type":"itemskill","skill":"MG_LIGHTNINGBOLT","level":3}, // Level 3 Lightening Bolt
    693: {"type":"itemskill","skill":"MG_LIGHTNINGBOLT","level":5}, // Level 5 Lightening Bolt
    694: {"type":"itemskill","skill":"MG_SOULSTRIKE","level":3}, // Level 3 Soul Strike
    695: {"type":"itemskill","skill":"MG_SOULSTRIKE","level":5}, // Level 5 Soul Strike
    696: {"type":"itemskill","skill":"MG_FIREBALL","level":1}, // Level 1 Fire Ball
    697: {"type":"itemskill","skill":"MG_FIREBALL","level":5}, // Level 5 Fire Ball
    698: {"type":"itemskill","skill":"MG_FIREWALL","level":1}, // Level 1 Fire Wall
    699: {"type":"itemskill","skill":"MG_FIREWALL","level":5}, // Level 5 Fire Wall
    700: {"type":"itemskill","skill":"MG_FROSTDIVER","level":1}, // Level 1 Frost Diver
    11500: {"type":"heal","hpMin":175,"hpMax":235}, // Light Yellow Potion
    11501: {"type":"heal","hpMin":325,"hpMax":405}, // Light White Potion
    11502: {"type":"heal","spMin":40,"spMax":60}, // Light Blue Potion
    11503: {"type":"heal","hpMin":400,"hpMax":500}, // WoE White Potion
    11504: {"type":"heal","spMin":50,"spMax":70}, // WoE Blue Potion
    11505: {"type":"heal","spMin":150,"spMax":150}, // Iris
    11506: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Fanta Orange
    11507: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Fanta Grape
    11508: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Karada Meguricha
    11509: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Black Tea Kochakaden
    11510: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Coca Cola Zero
    11511: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Diet Coca Cola
    11512: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Coca Cola
    11513: {"type":"heal","hpMin":5,"hpMax":25}, // Protect Neck Candy
    11514: {"type":"heal","hpMin":335,"hpMax":415}, // Enriched Slim Pot
    11515: {"type":"heal","hpMin":300,"hpMax":400}, // Coconut
    11516: {"type":"heal","hpMin":16,"hpMax":22}, // Asai Fruit
    11517: {"type":"heal","hpMin":400,"hpMax":600}, // Puri Potion
    11518: {"type":"heal","spMin":5,"spMax":5}, // Blue Potion
    11519: {"type":"heal","hpMin":170,"hpMax":250}, // Beef Toast
    11520: {"type":"heal","spMin":50,"spMax":80}, // Mora Mandar
    11521: {"type":"heal","hpMin":400,"hpMax":800,"spMin":50,"spMax":80}, // Pingui Berry Juice
    11522: {"type":"heal","hpMin":400,"hpMax":800}, // Red Raffle Sap
    11523: {"type":"heal","hpMin":600,"hpMax":1000}, // Yellow Raffle Sap
    11524: {"type":"heal","hpMin":800,"hpMax":1200}, // White Raffle Sap
    11525: {"type":"heal","hpMin":1500,"hpMax":2000}, // Mora HIp Tea
    11526: {"type":"heal","spMin":120,"spMax":160}, // Rafflecino
    11527: {"type":"heal","hpMin":1200,"hpMax":1200,"spMin":440,"spMax":440}, // Baklava
    11528: {"type":"heal","hpMin":300,"hpMax":300,"spMin":240,"spMax":240}, // Kanafeh
    11529: {"type":"heal","hpMin":120,"hpMax":120,"spMin":60,"spMax":60}, // Maamoul
    11530: {"type":"heal","hpMin":30,"hpMax":30}, // Jujube
    11531: {"type":"heal","spMin":10,"spMax":10}, // Coffee
    11701: {"type":"heal","hpMin":105,"hpMax":145}, // Girl's Bouquet
    11703: {"type":"heal","spMin":25,"spMax":35}, // Mystery Blood
    11704: {"type":"heal","hpMin":70,"hpMax":90}, // Ketupat
    11705: {"type":"heal","hpMin":425,"hpMax":425}, // Children's Potion
    11706: {"type":"heal","hpMin":700,"hpMax":1000}, // Steak
    11707: {"type":"heal","spMin":100,"spMax":200}, // Roast Beef
    11708: {"type":"heal","hpMin":30,"hpMax":50,"spMin":1,"spMax":5}, // Fore Flank Sirloin
    11709: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Fanta Zero Lemon
    11710: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Sakura Mist
    11711: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Sakura Milk Tea
    11712: {"type":"heal","hpMin":50,"hpMax":70,"spMin":10,"spMax":12}, // Flower
    12000: {"type":"itemskill","skill":"MG_FROSTDIVER","level":5}, // Level 5 Frost Diver
    12001: {"type":"itemskill","skill":"AL_HEAL","level":3}, // Level 3 Heal
    12002: {"type":"itemskill","skill":"AL_HEAL","level":5}, // Level 5 Heal
    12003: {"type":"itemskill","skill":"AL_TELEPORT","level":1}, // Level 1 Teleport
    12016: {"type":"sc_start","status":"SC_SPEEDUP1","duration":5000,"value":50}, // Speed Potion
    12017: {"type":"sc_start","status":"SC_SLOWDOWN","duration":5000,"value":100}, // Slow Potion
    12019: {"type":"itemskill","skill":"ALL_RESURRECTION","level":2}, // Holy Egg
    12020: {"type":"itemskill","skill":"ITEM_ENCHANTARMS","level":8}, // Cursed Water
    12021: {"type":"heal","hpMin":70,"hpMax":99}, // Pork
    12022: {"type":"heal","hpMin":70,"hpMax":99}, // Galbi
    12027: {"type":"percentheal","hp":9,"sp":0}, // Giggling Box
    12028: {"type":"sc_start","status":"SC_SPEEDUP0","duration":20000,"value":25}, // Box of Thunder
    12029: {"type":"itemskill","skill":"AC_CONCENTRATION","level":1}, // Box of Gloom
    12030: {"type":"sc_start","status":"SC_ATKPOTION","duration":60000,"value":20}, // Box of Resentment
    12031: {"type":"sc_start","status":"SC_MATKPOTION","duration":60000,"value":20}, // Box of Drowsiness
    12032: {"type":"itemskill","skill":"ITEM_ENCHANTARMS","level":2}, // Box of Storms
    12033: {"type":"sc_start","status":"SC_Intravision","duration":30000,"value":0}, // Box of Sunlight
    12034: {"type":"percentheal","hp":0,"sp":9}, // Box of Panting
    12041: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":1}]}, // Fried Grasshopper Legs
    12042: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":2}]}, // Seasoned Sticky Webfoot
    12043: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":3}]}, // Bomber Steak
    12044: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":4}]}, // Herb Marinade Beef
    12045: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":5}]}, // Lutie Lady's Pancake
    12046: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":1}]}, // Grape Juice Herbal Tea
    12047: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":2}]}, // Autumn Red Tea
    12048: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":3}]}, // Honey Herbal Tea
    12049: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":4}]}, // Morocc Fruit Wine
    12050: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":10},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":5}]}, // Mastela Fruit Wine
    12051: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":1}]}, // Steamed Crab Nippers
    12052: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":2}]}, // Assorted Seafood
    12053: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":3}]}, // Clam Soup
    12054: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":4}]}, // Seasoned Jellyfish
    12055: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":5}]}, // Spicy Fried Bao
    12056: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":1},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":1}]}, // Frog Egg Squid Ink Soup
    12057: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":1},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":2}]}, // Smooth Noodle
    12058: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":1},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":3}]}, // Tentacle Cheese Gratin
    12059: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":1},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":4}]}, // Lutie Cold Noodle
    12060: {"type":"multi","effects":[{"type":"percentheal","hp":6,"sp":2},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":5}]}, // Steamed Bat Wing in Pumpkin
    12061: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":2},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":1}]}, // Honey Grape Juice
    12062: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":2},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":2}]}, // Chocolate Mousse Cake
    12063: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":2},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":3}]}, // Fruit Mix
    12064: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":2},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":4}]}, // Cream Sandwich
    12065: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":5},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":5}]}, // Green Salad
    12066: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":1}]}, // Fried Monkey Tails
    12067: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":2}]}, // Mixed Juice
    12068: {"type":"multi","effects":[{"type":"percentheal","hp":4,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":3}]}, // Fried Sweet Potato
    12069: {"type":"multi","effects":[{"type":"percentheal","hp":4,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":4}]}, // Steamed Ancient Lips
    12070: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":5}]}, // Fried Scorpion Tails
    12071: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":2},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":6}]}, // Shiny Marinade Beef
    12072: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":4},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":7}]}, // Whole Roast
    12073: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":6},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":8}]}, // Bearfoot Special
    12074: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":8},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":9}]}, // Tendon Satay
    12075: {"type":"multi","effects":[{"type":"percentheal","hp":20,"sp":20},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":10}]}, // Steamed Tongue
    12076: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":10},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":6}]}, // Red Mushroom Wine
    12077: {"type":"multi","effects":[{"type":"percentheal","hp":4,"sp":10},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":7}]}, // Special Royal Jelly Herbal Tea
    12078: {"type":"multi","effects":[{"type":"percentheal","hp":6,"sp":10},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":8}]}, // Royal Family Tea
    12079: {"type":"multi","effects":[{"type":"percentheal","hp":8,"sp":15},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":9}]}, // Tristan XII
    12080: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":20},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":10}]}, // Dragon Breath Cocktail
    12081: {"type":"multi","effects":[{"type":"percentheal","hp":13,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":6}]}, // Awfully Bitter Bracer
    12082: {"type":"multi","effects":[{"type":"percentheal","hp":16,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":7}]}, // Sumptuous Feast
    12083: {"type":"multi","effects":[{"type":"percentheal","hp":19,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":8}]}, // Giant Burito
    12084: {"type":"multi","effects":[{"type":"percentheal","hp":22,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":9}]}, // Ascending Dragon Soup
    12085: {"type":"multi","effects":[{"type":"percentheal","hp":25,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":10}]}, // Immortal Stew
    12086: {"type":"multi","effects":[{"type":"percentheal","hp":7,"sp":2},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":6}]}, // Chile Shrimp Gratin
    12087: {"type":"multi","effects":[{"type":"percentheal","hp":8,"sp":2},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":7}]}, // Steamed Alligator with Vegetable
    12088: {"type":"multi","effects":[{"type":"percentheal","hp":9,"sp":2},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":8}]}, // Incredibly Spicy Curry
    12089: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":2},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":9}]}, // Special Meat Stew
    12090: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":10}]}, // Steamed Desert Scorpions
    12091: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":6},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":6}]}, // Peach Cake
    12092: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":7},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":7}]}, // Soul Haunted Bread
    12093: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":8},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":8}]}, // Special Toast
    12094: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":9},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":9}]}, // Heavenly Fruit Juice
    12095: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":10},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":10}]}, // Hwergelmir's Tonic
    12096: {"type":"multi","effects":[{"type":"percentheal","hp":6,"sp":3},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":6}]}, // Lucky Soup
    12097: {"type":"multi","effects":[{"type":"percentheal","hp":7,"sp":3},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":7}]}, // Assorted Shish Kebob
    12098: {"type":"multi","effects":[{"type":"percentheal","hp":9,"sp":3},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":8}]}, // Strawberry Flavored Rice Ball
    12099: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":4},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":9}]}, // Blood Flavored Soda
    12100: {"type":"multi","effects":[{"type":"percentheal","hp":14,"sp":8},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":10}]}, // Cooked Nine Tail's Tails
    12112: {"type":"sc_start","status":"SC_Curse","duration":10000,"value":1}, // Tropical Sograt
    12113: {"type":"sc_start","status":"SC_Stun","duration":10000,"value":1}, // Vermilion on the Beach
    12114: {"type":"itemskill","skill":"ITEM_ENCHANTARMS","level":4}, // Elemental Converter
    12115: {"type":"itemskill","skill":"ITEM_ENCHANTARMS","level":2}, // Elemental Converter
    12116: {"type":"itemskill","skill":"ITEM_ENCHANTARMS","level":3}, // Elemental Converter
    12117: {"type":"itemskill","skill":"ITEM_ENCHANTARMS","level":5}, // Elemental Converter
    12122: {"type":"sc_start","status":"SC_HITFOOD","duration":1800000,"value":30}, // Sesame Pastry
    12123: {"type":"sc_start","status":"SC_FLEEFOOD","duration":1800000,"value":30}, // Honey Pastry
    12124: {"type":"multi","effects":[{"type":"sc_start","status":"SC_BATKFOOD","duration":60000,"value":10},{"type":"sc_start","status":"SC_MATKFOOD","duration":60000,"value":10}]}, // Rainbow Cake
    12132: {"type":"sc_start","status":"SC_Xmas","duration":600000,"value":0}, // Santa's Bag
    12133: {"type":"percentheal","hp":50,"sp":50}, // McDonald's Ice Cone
    12135: {"type":"percentheal","hp":50,"sp":50}, // Green Ale
    12142: {"type":"sc_start","status":"SC_AGIFOOD","duration":1800000,"value":10}, // Book of Magic
    12188: {"type":"percentheal","hp":50,"sp":50}, // Grace Moon Cake
    12192: {"type":"percentheal","hp":5,"sp":5}, // Pumpkin Pie
    12195: {"type":"percentheal","hp":0,"sp":20}, // Plain Rice Cake
    12196: {"type":"percentheal","hp":50,"sp":0}, // Hearty Rice Cake
    12197: {"type":"percentheal","hp":10,"sp":10}, // Salty Rice Cake
    12198: {"type":"sc_start","status":"SC_INCLUK","duration":1200000,"value":21}, // Lucky Rice Cake
    12200: {"type":"itemskill","skill":"PR_MAGNIFICAT","level":3}, // X-mas Cake
    12202: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_FOOD_STR_CASH","duration":1800000,"value":10}]}, // Steamed Tongue
    12203: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_FOOD_AGI_CASH","duration":1800000,"value":10}]}, // Steamed Scorpion
    12204: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_FOOD_INT_CASH","duration":1800000,"value":10}]}, // Dragon Breath Cocktail
    12205: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_FOOD_DEX_CASH","duration":1800000,"value":10}]}, // Hwergelmir's Tonic
    12206: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_FOOD_LUK_CASH","duration":1800000,"value":10}]}, // Cooked Nine Tail's Tails
    12207: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_FOOD_VIT_CASH","duration":1800000,"value":10}]}, // Stew Of Immortality
    12208: {"type":"sc_start","status":"SC_EXPBOOST","duration":1800000,"value":50}, // Battle Manual
    12209: {"type":"sc_start","status":"SC_LIFEINSURANCE","duration":1800000,"value":0}, // Life Insurance
    12210: {"type":"sc_start","status":"SC_ITEMBOOST","duration":1800000,"value":100}, // Bubble Gum
    12214: {"type":"sc_start","status":"SC_BOSSMAPINFO","duration":600000,"value":0}, // Convex Mirror
    12215: {"type":"sc_start","status":"SC_BLESSING","duration":240000,"value":10}, // LV10 Blessing Scroll
    12216: {"type":"sc_start","status":"SC_INCREASEAGI","duration":240000,"value":10}, // LV10 Agil Scroll
    12217: {"type":"sc_start","status":"SC_ASPERSIO","duration":180000,"value":5}, // LV5 Aspersio Scroll
    12218: {"type":"sc_start","status":"SC_ASSUMPTIO","duration":100000,"value":5}, // LV5 Assumptio Scroll
    12219: {"type":"sc_start","status":"SC_WINDWALK","duration":250000,"value":5}, // LV10 Wind Walker Scroll
    12220: {"type":"sc_start","status":"SC_ADRENALINE","duration":150000,"value":5}, // LV5 Adrenaline Scroll
    12226: {"type":"multi","effects":[{"type":"percentheal","hp":100,"sp":100},{"type":"sc_start","status":"SC_SPEEDUP0","duration":5400000,"value":25},{"type":"sc_start","status":"SC_STRFOOD","duration":5400000,"value":10},{"type":"sc_start","status":"SC_DEXFOOD","duration":5400000,"value":5},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":22},{"type":"sc_start","status":"SC_MATKFOOD","duration":5400000,"value":15}]}, // Examination 1
    12227: {"type":"multi","effects":[{"type":"percentheal","hp":100,"sp":100},{"type":"sc_start","status":"SC_SPEEDUP0","duration":5400000,"value":25},{"type":"sc_start","status":"SC_INTFOOD","duration":5400000,"value":8},{"type":"sc_start","status":"SC_VITFOOD","duration":5400000,"value":7},{"type":"sc_start","status":"SC_LUKFOOD","duration":5400000,"value":7},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":10}]}, // Examination 2
    12228: {"type":"multi","effects":[{"type":"percentheal","hp":100,"sp":100},{"type":"sc_start","status":"SC_SPEEDUP0","duration":5400000,"value":25},{"type":"sc_start","status":"SC_AGIFOOD","duration":5400000,"value":15},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":52},{"type":"sc_start","status":"SC_MATKFOOD","duration":5400000,"value":10}]}, // Examination 3
    12229: {"type":"multi","effects":[{"type":"percentheal","hp":100,"sp":100},{"type":"sc_start","status":"SC_SPEEDUP0","duration":5400000,"value":25},{"type":"sc_start","status":"SC_STRFOOD","duration":5400000,"value":3},{"type":"sc_start","status":"SC_AGIFOOD","duration":5400000,"value":5},{"type":"sc_start","status":"SC_VITFOOD","duration":5400000,"value":10},{"type":"sc_start","status":"SC_MATKFOOD","duration":5400000,"value":52}]}, // Examination 4
    12230: {"type":"multi","effects":[{"type":"percentheal","hp":100,"sp":100},{"type":"sc_start","status":"SC_SPEEDUP0","duration":5400000,"value":25},{"type":"sc_start","status":"SC_INTFOOD","duration":5400000,"value":3},{"type":"sc_start","status":"SC_DEXFOOD","duration":5400000,"value":12},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":20},{"type":"sc_start","status":"SC_MATKFOOD","duration":5400000,"value":20}]}, // Examination 5
    12231: {"type":"multi","effects":[{"type":"percentheal","hp":100,"sp":100},{"type":"sc_start","status":"SC_SPEEDUP0","duration":5400000,"value":25},{"type":"sc_start","status":"SC_STRFOOD","duration":5400000,"value":6},{"type":"sc_start","status":"SC_DEXFOOD","duration":5400000,"value":6},{"type":"sc_start","status":"SC_AGIFOOD","duration":5400000,"value":6},{"type":"sc_start","status":"SC_INTFOOD","duration":5400000,"value":6},{"type":"sc_start","status":"SC_VITFOOD","duration":5400000,"value":6},{"type":"sc_start","status":"SC_LUKFOOD","duration":5400000,"value":6},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":24},{"type":"sc_start","status":"SC_MATKFOOD","duration":5400000,"value":24}]}, // Examination 6
    12232: {"type":"multi","effects":[{"type":"sc_start","status":"SC_ASPDPOTION1","duration":900000,"value":0},{"type":"sc_start","status":"SC_SPEEDUP0","duration":900000,"value":25}]}, // Ginger Bread
    12233: {"type":"percentheal","hp":100,"sp":100}, // Kvass
    12234: {"type":"percentheal","hp":25,"sp":0}, // Fierce Cacao 99%
    12235: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_BLESSING","duration":240000,"value":10}]}, // Chocolate Strawberry
    12236: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"itemskill","skill":"AL_ANGELUS","level":5}]}, // Chocolate Tart
    12237: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_Poison","duration":18000,"value":0},{"type":"sc_start","status":"SC_Bleeding","duration":18000,"value":0}]}, // Junky Chocolate
    12238: {"type":"sc_start","status":"SC_Poison","duration":50000,"value":0}, // New Year Rice Cake
    12239: {"type":"sc_start","status":"SC_Poison","duration":50000,"value":0}, // New Year Rice Cake
    12241: {"type":"sc_start","status":"SC_ASPDPOTION0","duration":1800000,"value":0}, // Mercenary Concentration Potion
    12242: {"type":"sc_start","status":"SC_ASPDPOTION1","duration":1800000,"value":0}, // Mercenary Awakening Potion
    12243: {"type":"sc_start","status":"SC_ASPDPOTION2","duration":1800000,"value":0}, // Mercenary Berserk Potion
    12245: {"type":"percentheal","hp":100,"sp":0}, // Green Ale
    12247: {"type":"sc_start","status":"SC_INCALLSTATUS","duration":600000,"value":3}, // Halo-Halo
    12250: {"type":"multi","effects":[{"type":"percentheal","hp":20,"sp":20},{"type":"sc_start","status":"SC_STRFOOD","duration":3600000,"value":10}]}, // Steamed Tongue
    12251: {"type":"multi","effects":[{"type":"percentheal","hp":15,"sp":5},{"type":"sc_start","status":"SC_AGIFOOD","duration":3600000,"value":10}]}, // Steamed Desert Scorpions
    12252: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":20},{"type":"sc_start","status":"SC_INTFOOD","duration":3600000,"value":10}]}, // Dragon Breath Cocktail
    12253: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":10},{"type":"sc_start","status":"SC_DEXFOOD","duration":3600000,"value":10}]}, // Hwergelmir's Tonic
    12254: {"type":"multi","effects":[{"type":"percentheal","hp":14,"sp":8},{"type":"sc_start","status":"SC_LUKFOOD","duration":3600000,"value":10}]}, // Cooked Nine Tail
    12255: {"type":"multi","effects":[{"type":"percentheal","hp":25,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":3600000,"value":10}]}, // Immortal Stew
    12257: {"type":"percentheal","hp":25,"sp":25}, // Cold Medicine
    12260: {"type":"sc_start","status":"SC_Summer","duration":600000,"value":0}, // Cool Summer Outfit
    12262: {"type":"sc_start","status":"SC_SPEEDUP0","duration":540000,"value":25}, // Authoritative Badge
    12263: {"type":"sc_start","status":"SC_EXPBOOST","duration":1800000,"value":50}, // Field Manual
    12264: {"type":"sc_start","status":"SC_ITEMBOOST","duration":1800000,"value":100}, // Bubble Gum
    12265: {"type":"sc_start","status":"SC_LIFEINSURANCE","duration":1800000,"value":0}, // Life Insurrance
    12266: {"type":"sc_start","status":"SC_HITFOOD","duration":180000,"value":30}, // Sesame Pastry
    12267: {"type":"sc_start","status":"SC_FLEEFOOD","duration":180000,"value":30}, // Honey Pastry
    12268: {"type":"multi","effects":[{"type":"sc_start","status":"SC_ATKPOTION","duration":60000,"value":10},{"type":"sc_start","status":"SC_MATKFOOD","duration":60000,"value":10}]}, // Rainbow Cake
    12269: {"type":"sc_start","status":"SC_ATKPOTION","duration":600000,"value":15}, // Tasty Pink Ration
    12270: {"type":"sc_start","status":"SC_MATKPOTION","duration":600000,"value":15}, // Tasty White Ration
    12271: {"type":"percentheal","hp":5,"sp":0}, // Military Ration A
    12272: {"type":"sc_start","status":"SC_HITFOOD","duration":600000,"value":33}, // Military Ration B
    12273: {"type":"sc_start","status":"SC_FLEEFOOD","duration":600000,"value":33}, // Military Ration C
    12274: {"type":"percentheal","hp":10,"sp":0}, // Daehwandan
    12275: {"type":"percentheal","hp":0,"sp":10}, // Taecheongdan
    12280: {"type":"sc_start","status":"SC_BENEDICTIO","duration":300000,"value":1}, // Holy Elemental Scroll
    12282: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCALLSTATUS","duration":5400000,"value":3},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":15},{"type":"sc_start","status":"SC_MATKPOTION","duration":5400000,"value":15}]}, // Internet Cafe1
    12283: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCSTR","duration":5400000,"value":8},{"type":"sc_start","status":"SC_INCDEX","duration":5400000,"value":4},{"type":"sc_start","status":"SC_INCAGI","duration":5400000,"value":6},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":32},{"type":"sc_start","status":"SC_INCFLEE","duration":5400000,"value":5}]}, // Internet Cafe2
    12284: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCINT","duration":5400000,"value":8},{"type":"sc_start","status":"SC_INCVIT","duration":5400000,"value":4},{"type":"sc_start","status":"SC_INCDEX","duration":5400000,"value":6},{"type":"sc_start","status":"SC_MATKPOTION","duration":5400000,"value":40}]}, // Internet Cafe3
    12285: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCDEX","duration":5400000,"value":8},{"type":"sc_start","status":"SC_INCLUK","duration":5400000,"value":4},{"type":"sc_start","status":"SC_INCAGI","duration":5400000,"value":6},{"type":"sc_start","status":"SC_ATKPOTION","duration":5400000,"value":24},{"type":"sc_start","status":"SC_MATKPOTION","duration":5400000,"value":24}]}, // Internet Cafe4
    12290: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_BLESSING","duration":120000,"value":5}]}, // Mysterious Can Magic Powder
    12291: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_INCREASEAGI","duration":120000,"value":5}]}, // Mysterious PET Bottle
    12292: {"type":"percentheal","hp":20,"sp":0}, // Unripe Fruit
    12293: {"type":"percentheal","hp":0,"sp":20}, // Dried Yggdrasilberry
    12298: {"type":"sc_start","status":"SC_SPCOST_RATE","duration":3600000,"value":15}, // SP Consumption Reduction Potion
    12299: {"type":"sc_start","status":"SC_COMMONSC_RESIST","duration":3600000,"value":10}, // Mega Resist Potion
    12310: {"type":"sc_start","status":"SC_FLEEFOOD","duration":300000,"value":10}, // Spray Of Flowers
    12311: {"type":"itemskill","skill":"ALL_PARTYFLEE","level":1}, // Huge Spray Of Flowers
    12312: {"type":"sc_start","status":"SC_EXPBOOST","duration":3600000,"value":50}, // Thick Battle Manual
    12313: {"type":"itemskill","skill":"ALL_ANGEL_PROTECT","level":1}, // Guardian Angel
    12319: {"type":"multi","effects":[{"type":"sc_start","status":"SC_ATKPOTION","duration":600000,"value":5},{"type":"sc_start","status":"SC_MATKPOTION","duration":600000,"value":5}]}, // Rune Strawberry Cake
    12320: {"type":"multi","effects":[{"type":"sc_start","status":"SC_HITFOOD","duration":600000,"value":10},{"type":"sc_start","status":"SC_FLEEFOOD","duration":600000,"value":20}]}, // Schwarzwald Pine Jubilee
    12321: {"type":"sc_start","status":"SC_INCCRI","duration":600000,"value":7}, // Arunafeltz Desert Sandwich
    12322: {"type":"percentheal","hp":5,"sp":5}, // Chocolate Pie
    12323: {"type":"itemskill","skill":"AL_TELEPORT","level":1}, // Novice Fly Wing
    12324: {"type":"itemskill","skill":"AL_TELEPORT","level":3}, // Novice Butterfly Wing
    12325: {"type":"itemskill","skill":"MC_IDENTIFY","level":1}, // Novice Magnifier
    12328: {"type":"sc_start","status":"SC_INCLUK","duration":3600000,"value":20}, // Charm Of Happiness
    12331: {"type":"percentheal","hp":6,"sp":0}, // Ginseng
    12332: {"type":"percentheal","hp":0,"sp":6}, // Fruit Juice
    12333: {"type":"percentheal","hp":0,"sp":15}, // Ancilla
    12335: {"type":"percentheal","hp":60,"sp":60}, // Grilled Delicious Skewer
    12336: {"type":"percentheal","hp":30,"sp":30}, // Grilled Mushroom
    12337: {"type":"percentheal","hp":20,"sp":20}, // Grilled Sausages
    12338: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCSTR","duration":180000,"value":2},{"type":"sc_start","status":"SC_INCINT","duration":180000,"value":2},{"type":"sc_start","status":"SC_INCAGI","duration":180000,"value":2}]}, // Grilled Corn
    12342: {"type":"sc_start","status":"SC_MANU_ATK","duration":600000,"value":10}, // Manuk's Opportunity
    12343: {"type":"sc_start","status":"SC_MANU_DEF","duration":600000,"value":10}, // Manuk's Courage
    12344: {"type":"sc_start","status":"SC_SPL_ATK","duration":600000,"value":10}, // Pinguicula's Fruit Jam
    12345: {"type":"sc_start","status":"SC_SPL_DEF","duration":600000,"value":10}, // Luciola's Honey Jam
    12347: {"type":"itemskill","skill":"ALL_REVERSEORCISH","level":1}, // Acorn Jelly
    12348: {"type":"sc_start","status":"SC_MANU_MATK","duration":600000,"value":10}, // Manuk's Faith
    12349: {"type":"sc_start","status":"SC_SPL_MATK","duration":600000,"value":10}, // Cornus' Tears
    12350: {"type":"multi","effects":[{"type":"itemskill","skill":"AL_ANGELUS","level":5},{"type":"sc_start","status":"SC_BLESSING","duration":120000,"value":5}]}, // Angeling Potion
    12351: {"type":"itemskill","skill":"MC_LOUD","level":1}, // Scream Megaphone
    12353: {"type":"sc_start","status":"SC_WATERWEAPON","duration":90000,"value":1}, // Small Bottle
    12354: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCMHPRATE","duration":600000,"value":3},{"type":"sc_start","status":"SC_INCMSPRATE","duration":600000,"value":3},{"type":"sc_start","status":"SC_INCHITRATE","duration":600000,"value":3},{"type":"sc_start","status":"SC_INCCRI","duration":600000,"value":7}]}, // Buche De Noel
    12376: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":0},{"type":"itemskill","skill":"PR_GLORIA","level":2}]}, // Mysterious Can2
    12377: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":3},{"type":"itemskill","skill":"PR_MAGNIFICAT","level":1}]}, // Mysterious PET Bottle2
    12378: {"type":"percentheal","hp":50,"sp":50}, // Rice Cake Soup
    12384: {"type":"itemskill","skill":"WL_FROSTMISTY","level":5}, // Rainbow Ruby
    12385: {"type":"itemskill","skill":"WL_CRIMSONROCK","level":5}, // Rainbow Ruby
    12386: {"type":"itemskill","skill":"WL_CHAINLIGHTNING","level":5}, // Rainbow Ruby
    12387: {"type":"itemskill","skill":"WL_EARTHSTRAIN","level":5}, // Rainbow Ruby
    12388: {"type":"itemskill","skill":"RK_CRUSHSTRIKE","level":1}, // Rhydo Runestone For Apprentice
    12389: {"type":"itemskill","skill":"RK_STORMBLAST","level":1}, // Pertz Runestone For Apprentice
    12390: {"type":"itemskill","skill":"RK_MILLENNIUMSHIELD","level":1}, // Verkana Runestone For Apprentice
    12392: {"type":"heal","hpMin":200,"hpMax":300}, // Repair A
    12393: {"type":"heal","hpMin":300,"hpMax":400}, // Repair B
    12394: {"type":"heal","hpMin":400,"hpMax":500}, // Repair C
    12396: {"type":"multi","effects":[{"type":"percentheal","hp":50,"sp":0},{"type":"percentheal","hp":0,"sp":50},{"type":"itemskill","skill":"AL_TELEPORT","level":1},{"type":"itemskill","skill":"AL_TELEPORT","level":3},{"type":"itemskill","skill":"ALL_REVERSEORCISH","level":1}]}, // Gift Box?
    12397: {"type":"multi","effects":[{"type":"itemskill","skill":"TF_DETOXIFY","level":1},{"type":"itemskill","skill":"TF_PICKSTONE","level":1},{"type":"itemskill","skill":"BA_FROSTJOKER","level":1},{"type":"itemskill","skill":"DC_SCREAM","level":1},{"type":"itemskill","skill":"AL_RUWACH","level":1}]}, // Gift Box?
    12401: {"type":"sc_start","status":"SC_INCINT","duration":300000,"value":40}, // Rune Kn Test Int
    12402: {"type":"percentheal","hp":5,"sp":5}, // 29Fruit
    12405: {"type":"multi","effects":[{"type":"percentheal","hp":30,"sp":30},{"type":"sc_start","status":"SC_BLESSING","duration":140000,"value":5}]}, // Underripe Yggseed
    12411: {"type":"sc_start","status":"SC_EXPBOOST","duration":900000,"value":200}, // HE Battle Manual
    12412: {"type":"sc_start","status":"SC_ITEMBOOST","duration":900000,"value":200}, // HE Bubble Gum
    12414: {"type":"multi","effects":[{"type":"sc_start","status":"SC_ASPDPOTION0","duration":1800000,"value":0},{"type":"sc_start","status":"SC_INCREASEAGI","duration":140000,"value":5}]}, // Guarana Candy
    12417: {"type":"sc_start","status":"SC_BOOST500","duration":500000,"value":10}, // Boost500
    12418: {"type":"sc_start","status":"SC_FULL_SWING_K","duration":500000,"value":50}, // Full SwingK
    12419: {"type":"sc_start","status":"SC_MANA_PLUS","duration":500000,"value":50}, // Mana Plus
    12420: {"type":"sc_start","status":"SC_MUSTLE_M","duration":500000,"value":5}, // Stamina Up M
    12421: {"type":"sc_start","status":"SC_LIFE_FORCE_F","duration":500000,"value":5}, // Falmons F
    12422: {"type":"percentheal","hp":1,"sp":0}, // HP Increase Potion (Small)
    12423: {"type":"percentheal","hp":2,"sp":0}, // HP Increase Potion (Medium)
    12424: {"type":"percentheal","hp":5,"sp":0}, // HP Increase Potion (Large)
    12425: {"type":"percentheal","hp":0,"sp":2}, // SP Increase Potion (Small)
    12426: {"type":"percentheal","hp":0,"sp":4}, // SP Increase Potion (Medium)
    12427: {"type":"percentheal","hp":0,"sp":8}, // SP Increase Potion (Large)
    12428: {"type":"sc_start","status":"SC_EXTRACT_WHITE_POTION_Z","duration":500000,"value":20}, // Concentrated White Potion Z
    12429: {"type":"sc_start","status":"SC_SAVAGE_STEAK","duration":300000,"value":20}, // Savage Full Roast
    12430: {"type":"sc_start","status":"SC_COCKTAIL_WARG_BLOOD","duration":300000,"value":20}, // Cocktail Warg Blood
    12431: {"type":"sc_start","status":"SC_MINOR_BBQ","duration":300000,"value":20}, // Minor Stew
    12432: {"type":"sc_start","status":"SC_SIROMA_ICE_TEA","duration":300000,"value":20}, // Siroma Iced Tea
    12433: {"type":"sc_start","status":"SC_DROCERA_HERB_STEAMED","duration":300000,"value":20}, // Drosera Herb Salad
    12434: {"type":"sc_start","status":"SC_PUTTI_TAILS_NOODLES","duration":300000,"value":20}, // Petite Tail Noodles
    12436: {"type":"multi","effects":[{"type":"heal","spMin":200,"spMax":200},{"type":"sc_start","status":"SC_VITATA_500","duration":500000,"value":0}]}, // Vitata 500
    12437: {"type":"sc_start","status":"SC_EXTRACT_SALAMINE_JUICE","duration":500000,"value":10}, // Concentrated Ceromain Soup
    12475: {"type":"multi","effects":[{"type":"heal","hpMin":500,"hpMax":500},{"type":"cure","cures":["SC_SILENCE","SC_BLEEDING","SC_POISON","SC_CURSE","SC_ORCISH","SC_CHANGEUNDEAD"]}]}, // Cure Free
    12704: {"type":"percentheal","hp":100,"sp":0}, // Elixir of Life
    12705: {"type":"sc_start","status":"SC_EXPBOOST","duration":1800000,"value":100}, // Noble Nameplate
    12706: {"type":"itemskill","skill":"PR_GLORIA","level":5}, // Lucky Cookie
    12707: {"type":"itemskill","skill":"PR_MAGNIFICAT","level":1}, // Lucky Cookie
    12708: {"type":"itemskill","skill":"PR_IMPOSITIO","level":3}, // Lucky Cookie
    12709: {"type":"percentheal","hp":30,"sp":30}, // Guyak Candy
    12710: {"type":"sc_start","status":"SC_SPEEDUP1","duration":300000,"value":50}, // Guyak Pudding
    12711: {"type":"heal","hpMin":50,"hpMax":90}, // Pretzel
    12712: {"type":"percentheal","hp":0,"sp":50}, // Green Beer
    12755: {"type":"multi","effects":[{"type":"itemskill","skill":"MO_CALLSPIRITS","level":3},{"type":"itemskill","skill":"MO_FINGEROFFENSIVE","level":5}]}, // Chinese Fireworks
    12928: {"type":"itemskill","skill":"PR_ASPERSIO","level":5}, // Sacred Scroll
    13830: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCSTR","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCAGI","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCVIT","duration":60000,"value":5}]}, // Stat Boost 1
    13831: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCINT","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCLUK","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCDEX","duration":60000,"value":5}]}, // Stat Boost 2
    13832: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCAGI","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCVIT","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCDEX","duration":60000,"value":5}]}, // Stat Boost 3
    13833: {"type":"multi","effects":[{"type":"sc_start","status":"SC_INCINT","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCVIT","duration":60000,"value":5},{"type":"sc_start","status":"SC_INCDEX","duration":60000,"value":5}]}, // Stat Boost 4
    14500: {"type":"sc_start","status":"SC_LIFEINSURANCE","duration":3600000,"value":0}, // Life Insurrance Certificate
    14509: {"type":"sc_start","status":"SC_ASPDPOTION0","duration":1800000,"value":0}, // Light Concentration Potion
    14510: {"type":"sc_start","status":"SC_ASPDPOTION1","duration":1800000,"value":0}, // Light Awakening Potion
    14511: {"type":"sc_start","status":"SC_ASPDPOTION2","duration":1800000,"value":0}, // Light Berserk Potion
    14512: {"type":"itemskill","skill":"WZ_METEOR","level":10}, // Meteor Storm Scroll
    14513: {"type":"itemskill","skill":"WZ_STORMGUST","level":10}, // Storm Gust Scroll
    14514: {"type":"itemskill","skill":"WZ_VERMILION","level":10}, // Lord of Vermilion Scroll
    14515: {"type":"itemskill","skill":"PR_LEXAETERNA","level":1}, // Lex Aeterna Scroll
    14516: {"type":"itemskill","skill":"PR_MAGNIFICAT","level":5}, // Magnificat Scroll
    14522: {"type":"percentheal","hp":100,"sp":0}, // Big Bun
    14523: {"type":"percentheal","hp":0,"sp":100}, // Pill
    14524: {"type":"percentheal","hp":100,"sp":100}, // Superb Fish Slice
    14525: {"type":"sc_start","status":"SC_ATKPOTION","duration":1800000,"value":10}, // Chewy Ricecake
    14526: {"type":"sc_start","status":"SC_MATKPOTION","duration":1800000,"value":10}, // Oriental Pastry
    14529: {"type":"itemskill","skill":"BS_GREED","level":1}, // Greed Scroll
    14530: {"type":"sc_start","status":"SC_FLEEFOOD","duration":1800000,"value":30}, // Evasion Scroll
    14531: {"type":"sc_start","status":"SC_HITFOOD","duration":1800000,"value":30}, // Concentration Scroll
    14532: {"type":"sc_start","status":"SC_EXPBOOST","duration":1800000,"value":25}, // Field Manual 25%
    14533: {"type":"sc_start","status":"SC_EXPBOOST","duration":1800000,"value":100}, // Field Manual 100%
    14536: {"type":"sc_start","status":"SC_INCCRI","duration":300000,"value":30}, // Abrasive
    14537: {"type":"sc_start","status":"SC_INCHEALRATE","duration":1800000,"value":20}, // Regeneration Potion
    14538: {"type":"sc_start","status":"SC_INCFLEE2","duration":60000,"value":20}, // Glass of Illusion
    14541: {"type":"sc_start","status":"SC_DEF_RATE","duration":60000,"value":3}, // Small Defense Potion
    14542: {"type":"sc_start","status":"SC_DEF_RATE","duration":180000,"value":3}, // Big Defense Potion
    14543: {"type":"sc_start","status":"SC_MDEF_RATE","duration":60000,"value":3}, // Small Magic Defense Potion
    14544: {"type":"sc_start","status":"SC_MDEF_RATE","duration":180000,"value":3}, // Big Magic Defense Potion
    14545: {"type":"sc_start","status":"SC_EXPBOOST","duration":1800000,"value":300}, // Field Manual 300%
    14551: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":1}]}, // Fried Grasshopper Legs
    14552: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":2}]}, // Seasoned Sticky Webfoot
    14553: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":3}]}, // Bomber Steak
    14554: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":1}]}, // Grape Juice Herbal Tea
    14555: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":2}]}, // Autumn Red Tea
    14556: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":5},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":3}]}, // Honey Herbal Tea
    14557: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":1}]}, // Steamed Crab Nippers
    14558: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":2}]}, // Assorted Seafood
    14559: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":3}]}, // Clam Soup
    14560: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":1},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":1}]}, // Frog Egg Squid Ink Soup
    14561: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":1},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":2}]}, // Smooth Noodle
    14562: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":1},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":3}]}, // Tentacle Cheese Gratin
    14563: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":2},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":1}]}, // Honey Grape Juice
    14564: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":2},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":2}]}, // Chocolate Mousse Cake
    14565: {"type":"multi","effects":[{"type":"percentheal","hp":2,"sp":2},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":3}]}, // Fruit Mix
    14566: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":1}]}, // Fried Monkey Tails
    14567: {"type":"multi","effects":[{"type":"percentheal","hp":3,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":2}]}, // Mixed Juice
    14568: {"type":"multi","effects":[{"type":"percentheal","hp":4,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":3}]}, // Fried Sweet Potato
    14575: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":0},{"type":"sc_start","status":"SC_STRFOOD","duration":1200000,"value":5}]}, // Lutie Lady's Pancake
    14576: {"type":"multi","effects":[{"type":"percentheal","hp":0,"sp":10},{"type":"sc_start","status":"SC_INTFOOD","duration":1200000,"value":5}]}, // Mastela Fruit Wine
    14577: {"type":"multi","effects":[{"type":"percentheal","hp":10,"sp":0},{"type":"sc_start","status":"SC_VITFOOD","duration":1200000,"value":5}]}, // Spicy Fried Bao
    14578: {"type":"multi","effects":[{"type":"percentheal","hp":6,"sp":2},{"type":"sc_start","status":"SC_AGIFOOD","duration":1200000,"value":5}]}, // Steamed Bat Wing in Pumpkin
    14579: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":5},{"type":"sc_start","status":"SC_DEXFOOD","duration":1200000,"value":5}]}, // Green Salad
    14580: {"type":"multi","effects":[{"type":"percentheal","hp":5,"sp":2},{"type":"sc_start","status":"SC_LUKFOOD","duration":1200000,"value":5}]}, // Fried Scorpion Tails
    14587: {"type":"itemskill","skill":"BS_REPAIRWEAPON","level":1}, // Equipment Repair Spell Book
    14588: {"type":"itemskill","skill":"CASH_BLESSING","level":10}, // Party Blessing 10 Scroll
    14589: {"type":"itemskill","skill":"CASH_INCAGI","level":10}, // Party Increase Agi 10 Scroll
    14590: {"type":"itemskill","skill":"CASH_ASSUMPTIO","level":5}, // Party Assumptio 5 Scroll
    14592: {"type":"sc_start","status":"SC_JEXPBOOST","duration":1800000,"value":50}, // JOB Battle Manual
    14593: {"type":"itemskill","skill":"HW_MAGICPOWER","level":10}, // Mystical Amplification Scroll
    14594: {"type":"itemskill","skill":"WZ_QUAGMIRE","level":5}, // Quagmire Scroll
    14601: {"type":"multi","effects":[{"type":"sc_start","status":"SC_FLEEFOOD","duration":300000,"value":30},{"type":"sc_start","status":"SC_HITFOOD","duration":300000,"value":30},{"type":"sc_start","status":"SC_ATKPOTION","duration":300000,"value":20},{"type":"sc_start","status":"SC_MATKPOTION","duration":300000,"value":20}]}, // Tyr's Blessing
    14607: {"type":"sc_start","status":"SC_INCALLSTATUS","duration":3600000,"value":3}, // Luxurious Western Food
    14608: {"type":"sc_start","status":"SC_INCALLSTATUS","duration":3600000,"value":6}, // Manchu-Han Imperial Feast
    14609: {"type":"percentheal","hp":10,"sp":10} // Spoiled Cuisine
};

module.exports = { ITEM_USE_EFFECTS };