// Auto-generated by scripts/generate_ro_items_migration.js
// Maps RO drop item names → database item_ids
// DO NOT EDIT MANUALLY — regenerate with: node scripts/generate_ro_items_migration.js

const RO_ITEM_NAME_TO_ID = {
    "Red Herb": 1006,
    "Yellow Herb": 1007,
    "Green Herb": 1008,
    "Blue Herb": 1009,
    "Hinalle": 1010,
    "Apple": 1011,
    "Banana": 1012,
    "Carrot": 1013,
    "Grape": 1014,
    "Meat": 1015,
    "Orange": 1016,
    "Strawberry": 1017,
    "Sweet Potato": 1018,
    "Honey": 1019,
    "Orange Juice": 1020,
    "Sweet Milk": 1021,
    "Rainbow Carrot": 1022,
    "Cacao": 1023,
    "Unripe Apple": 1024,
    "Center Potion": 1025,
    "Karvodailnirol": 1026,
    "Leaflet Of Hinal": 1027,
    "Wing Of Butterfly": 1028,
    "Wing Of Fly": 1029,
    "Wind Scroll 1 3": 1030,
    "Tree Of Archer 1": 1031,
    "Tree Of Archer 2": 1032,
    "Tree Of Archer 3": 1033,
    "Jellopy": 2009,
    "Fluff": 2010,
    "Shell": 2011,
    "Feather": 2012,
    "Mushroom Spore": 2013,
    "Talon": 2014,
    "Tree Root": 2015,
    "Tooth Of Bat": 2016,
    "Bee Sting": 2017,
    "Grasshopper's Leg": 2018,
    "Skel Bone": 2019,
    "Decayed Nail": 2020,
    "Sticky Webfoot": 2021,
    "Spawn": 2022,
    "Yoyo Tail": 2023,
    "Raccoon Leaf": 2024,
    "Stem": 2025,
    "Powder Of Butterfly": 2026,
    "Poison Spore": 2027,
    "Shoot": 2028,
    "Resin": 2029,
    "Feather Of Birds": 2030,
    "Bill Of Birds": 2031,
    "Animal's Skin": 2032,
    "Flower": 2033,
    "Clover": 2034,
    "Four Leaf Clover": 2035,
    "Chrysalis": 2036,
    "Sticky Mucus": 2037,
    "Garlet": 2038,
    "Empty Bottle": 2039,
    "Iron Ore": 2040,
    "Iron": 2041,
    "Phracon": 2042,
    "Oridecon Stone": 2043,
    "Wind Of Verdure": 2044,
    "Yellow Gemstone": 2045,
    "Azure Jewel": 2046,
    "Bluish Green Jewel": 2047,
    "Cardinal Jewel": 2048,
    "White Jewel": 2049,
    "Zargon": 2050,
    "Yellow Live": 2051,
    "Wooden Block": 2052,
    "Arrow": 2053,
    "Chonchon Doll": 2054,
    "Grasshopper Doll": 2055,
    "Monkey Doll": 2056,
    "Raccoondog Doll": 2057,
    "Spore Doll": 2058,
    "Knife": 3007,
    "Cutter": 3008,
    "Main Gauche": 3009,
    "Falchion": 3010,
    "Mace": 3011,
    "Rod": 3012,
    "Bow": 3013,
    "Javelin": 3014,
    "Spear": 3015,
    "Axe": 3016,
    "Club": 3017,
    "Wand": 3018,
    "Guitar Of Vast Land": 3019,
    "Whip Of Earth": 3020,
    "Guard": 4004,
    "Hat": 4005,
    "Sandals": 4006,
    "Silk Robe": 4007,
    "Ribbon": 4008,
    "Cat Hairband": 4009,
    "Skul Ring": 4010,
    "Green Feeler": 4011,
    "Pierrot Nose": 4012,
    "Horrendous Mouth": 4013,
    "Fancy Flower": 4014,
    "Poring Card": 5001,
    "Lunatic Card": 5002,
    "Fabre Card": 5003,
    "Pupa Card": 5004,
    "Drops Card": 5005,
    "Chonchon Card": 5006,
    "Condor Card": 5007,
    "Wilow Card": 5008,
    "Roda Frog Card": 5009,
    "Hornet Card": 5010,
    "Rocker Card": 5011,
    "Farmiliar Card": 5012,
    "Savage Babe Card": 5013,
    "Spore Card": 5014,
    "Zombie Card": 5015,
    "Skeleton Card": 5016,
    "Creamy Card": 5017,
    "Poporing Card": 5018,
    "Pecopeco Card": 5019,
    "Mandragora Card": 5020,
    "Poison Spore Card": 5021,
    "Smokie Card": 5022,
    "Yoyo Card": 5023
};

// Existing game items to add as extra drops on RO monsters
// Maps item_id → array of { monster: templateKey, chance: dropChance }
const EXISTING_ITEM_EXTRA_DROPS = {
    "1001": [
        {
            "monster": "poring",
            "chance": 0.05
        },
        {
            "monster": "lunatic",
            "chance": 0.04
        },
        {
            "monster": "fabre",
            "chance": 0.04
        },
        {
            "monster": "drops",
            "chance": 0.05
        },
        {
            "monster": "chonchon",
            "chance": 0.06
        },
        {
            "monster": "spore",
            "chance": 0.07
        },
        {
            "monster": "zombie",
            "chance": 0.08
        },
        {
            "monster": "skeleton",
            "chance": 0.08
        }
    ],
    "1002": [
        {
            "monster": "rocker",
            "chance": 0.03
        },
        {
            "monster": "hornet",
            "chance": 0.03
        },
        {
            "monster": "zombie",
            "chance": 0.04
        },
        {
            "monster": "skeleton",
            "chance": 0.04
        },
        {
            "monster": "creamy",
            "chance": 0.04
        },
        {
            "monster": "pecopeco",
            "chance": 0.05
        },
        {
            "monster": "poison_spore",
            "chance": 0.05
        }
    ],
    "1005": [
        {
            "monster": "savage_babe",
            "chance": 0.06
        },
        {
            "monster": "condor",
            "chance": 0.04
        },
        {
            "monster": "pecopeco",
            "chance": 0.05
        },
        {
            "monster": "yoyo",
            "chance": 0.04
        }
    ],
    "2001": [
        {
            "monster": "poring",
            "chance": 0.5
        },
        {
            "monster": "drops",
            "chance": 0.5
        },
        {
            "monster": "poporing",
            "chance": 0.4
        }
    ],
    "2002": [
        {
            "monster": "poring",
            "chance": 0.15
        },
        {
            "monster": "poporing",
            "chance": 0.2
        },
        {
            "monster": "poison_spore",
            "chance": 0.15
        }
    ],
    "2003": [
        {
            "monster": "pupa",
            "chance": 0.4
        },
        {
            "monster": "chonchon",
            "chance": 0.25
        }
    ],
    "2004": [
        {
            "monster": "lunatic",
            "chance": 0.15
        },
        {
            "monster": "condor",
            "chance": 0.2
        }
    ],
    "2005": [
        {
            "monster": "spore",
            "chance": 0.4
        },
        {
            "monster": "poison_spore",
            "chance": 0.35
        }
    ],
    "2006": [
        {
            "monster": "hornet",
            "chance": 0.3
        },
        {
            "monster": "chonchon",
            "chance": 0.25
        },
        {
            "monster": "rocker",
            "chance": 0.2
        }
    ],
    "2007": [
        {
            "monster": "fabre",
            "chance": 0.15
        },
        {
            "monster": "roda_frog",
            "chance": 0.1
        },
        {
            "monster": "mandragora",
            "chance": 0.15
        }
    ],
    "2008": [
        {
            "monster": "fabre",
            "chance": 0.4
        },
        {
            "monster": "lunatic",
            "chance": 0.15
        }
    ],
    "3001": [
        {
            "monster": "poring",
            "chance": 0.01
        },
        {
            "monster": "skeleton",
            "chance": 0.02
        }
    ],
    "3004": [
        {
            "monster": "skeleton",
            "chance": 0.01
        },
        {
            "monster": "zombie",
            "chance": 0.01
        }
    ],
    "4001": [
        {
            "monster": "pupa",
            "chance": 0.02
        },
        {
            "monster": "spore",
            "chance": 0.01
        }
    ],
    "4002": [
        {
            "monster": "skeleton",
            "chance": 0.01
        },
        {
            "monster": "zombie",
            "chance": 0.01
        }
    ]
};

module.exports = { RO_ITEM_NAME_TO_ID, EXISTING_ITEM_EXTRA_DROPS };
