/**
 * Ragnarok Online Skill Data — Second Class Skills (2-1 and 2-2)
 * Knight, Crusader, Wizard, Sage, Hunter, Bard, Dancer, Priest, Monk, Assassin, Rogue, Blacksmith, Alchemist
 */
'use strict';

function genLevels(count, fn) {
    return Array.from({ length: count }, (_, i) => fn(i));
}

module.exports = [
    // === KNIGHT (IDs 700-719) ===
    { id: 700, name: 'spear_mastery', displayName: 'Spear Mastery', classId: 'knight', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases ATK with Spears.', icon: 'spear_mastery', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*4, duration: 0 })) },
    { id: 701, name: 'pierce', displayName: 'Pierce', classId: 'knight', maxLevel: 10, type: 'active', targetType: 'single', element: 'neutral', range: 300, description: 'Multi-hit spear thrust based on target size.', icon: 'pierce', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 700, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 7, castTime: 0, cooldown: 500, effectValue: 100+i*10, duration: 0 })) },
    { id: 702, name: 'spear_stab', displayName: 'Spear Stab', classId: 'knight', maxLevel: 10, type: 'active', targetType: 'single', element: 'neutral', range: 300, description: 'Push enemy back with spear.', icon: 'spear_stab', treeRow: 2, treeCol: 0, prerequisites: [{ skillId: 701, level: 5 }], levels: genLevels(10, i => ({ level: i+1, spCost: 9, castTime: 0, cooldown: 500, effectValue: 120+i*20, duration: 0 })) },
    { id: 703, name: 'brandish_spear', displayName: 'Brandish Spear', classId: 'knight', maxLevel: 10, type: 'active', targetType: 'aoe', element: 'neutral', range: 300, description: 'Wide spear AoE. Must be mounted.', icon: 'brandish_spear', treeRow: 3, treeCol: 0, prerequisites: [{ skillId: 702, level: 3 }, { skillId: 701, level: 5 }], levels: genLevels(10, i => ({ level: i+1, spCost: 12, castTime: 0, cooldown: 1000, effectValue: 100+i*20, duration: 0 })) },
    { id: 704, name: 'spear_boomerang', displayName: 'Spear Boomerang', classId: 'knight', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 600, description: 'Throw spear at distant enemy.', icon: 'spear_boomerang', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 701, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 10, castTime: 0, cooldown: 1000, effectValue: 150+i*50, duration: 0 })) },
    { id: 705, name: 'two_hand_quicken', displayName: 'Two-Hand Quicken', classId: 'knight', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Greatly increase ASPD with 2H Swords.', icon: 'two_hand_quicken', treeRow: 0, treeCol: 2, prerequisites: [{ skillId: 101, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 14+i*2, castTime: 0, cooldown: 0, effectValue: i+1, duration: 30000+i*15000 })) },
    { id: 706, name: 'auto_counter', displayName: 'Auto Counter', classId: 'knight', maxLevel: 5, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Counter next melee attack.', icon: 'auto_counter', treeRow: 1, treeCol: 2, prerequisites: [{ skillId: 705, level: 1 }], levels: genLevels(5, i => ({ level: i+1, spCost: 3, castTime: 0, cooldown: 500, effectValue: 100, duration: 400+i*200 })) },
    { id: 707, name: 'bowling_bash', displayName: 'Bowling Bash', classId: 'knight', maxLevel: 10, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: 'Launch enemies into each other.', icon: 'bowling_bash', treeRow: 2, treeCol: 2, prerequisites: [{ skillId: 103, level: 10 }, { skillId: 705, level: 3 }, { skillId: 706, level: 3 }], levels: genLevels(10, i => ({ level: i+1, spCost: 13+i, castTime: 0, cooldown: 500, effectValue: 140+i*40, duration: 0 })) },
    { id: 708, name: 'riding', displayName: 'Riding', classId: 'knight', maxLevel: 1, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Ride a Peco Peco.', icon: 'riding', treeRow: 0, treeCol: 3, prerequisites: [{ skillId: 106, level: 1 }], levels: [{ level: 1, spCost: 0, castTime: 0, cooldown: 0, effectValue: 0, duration: 0 }] },
    { id: 709, name: 'cavalry_mastery', displayName: 'Cavalry Mastery', classId: 'knight', maxLevel: 5, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Reduce mounted speed penalty.', icon: 'cavalry_mastery', treeRow: 1, treeCol: 3, prerequisites: [{ skillId: 708, level: 1 }], levels: genLevels(5, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*20, duration: 0 })) },

    // === CRUSADER (IDs 1300-1319) ===
    { id: 1300, name: 'faith', displayName: 'Faith', classId: 'crusader', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases Max HP and holy resistance.', icon: 'faith', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*200, duration: 0 })) },
    { id: 1301, name: 'guard', displayName: 'Guard', classId: 'crusader', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Block physical attacks with shield.', icon: 'guard', treeRow: 0, treeCol: 1, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 10, castTime: 0, cooldown: 0, effectValue: 3*(i+1), duration: 300000 })) },
    { id: 1302, name: 'holy_cross', displayName: 'Holy Cross', classId: 'crusader', maxLevel: 10, type: 'active', targetType: 'single', element: 'holy', range: 150, description: 'Holy attack. 2x vs Undead.', icon: 'holy_cross', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 1300, level: 3 }], levels: genLevels(10, i => ({ level: i+1, spCost: 11+i, castTime: 0, cooldown: 500, effectValue: 135+i*35, duration: 0 })) },
    { id: 1303, name: 'grand_cross', displayName: 'Grand Cross', classId: 'crusader', maxLevel: 10, type: 'active', targetType: 'aoe', element: 'holy', range: 0, description: 'Massive holy AoE. Costs HP.', icon: 'grand_cross', treeRow: 2, treeCol: 0, prerequisites: [{ skillId: 1302, level: 6 }, { skillId: 1300, level: 10 }], levels: genLevels(10, i => ({ level: i+1, spCost: 37+i*3, castTime: 3000, cooldown: 5000, effectValue: 140+i*40, duration: 0 })) },
    { id: 1304, name: 'shield_charge', displayName: 'Shield Charge', classId: 'crusader', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: 'Bash with shield, push back.', icon: 'shield_charge', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1301, level: 5 }], levels: genLevels(5, i => ({ level: i+1, spCost: 10, castTime: 0, cooldown: 500, effectValue: 120+i*30, duration: 0 })) },
    { id: 1305, name: 'shield_boomerang', displayName: 'Shield Boomerang', classId: 'crusader', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 600, description: 'Throw shield at target.', icon: 'shield_boomerang', treeRow: 2, treeCol: 1, prerequisites: [{ skillId: 1304, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 12, castTime: 0, cooldown: 700, effectValue: 130+i*20, duration: 0 })) },
    { id: 1306, name: 'devotion', displayName: 'Devotion', classId: 'crusader', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 450, description: 'Take damage for an ally.', icon: 'devotion', treeRow: 0, treeCol: 2, prerequisites: [{ skillId: 1301, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 25, castTime: 3000, cooldown: 0, effectValue: i+1, duration: 30000+i*15000 })) },

    // === WIZARD (IDs 800-819) ===
    { id: 800, name: 'jupitel_thunder', displayName: 'Jupitel Thunder', classId: 'wizard', maxLevel: 10, type: 'active', targetType: 'single', element: 'wind', range: 450, description: 'Multi-hit lightning ball with knockback.', icon: 'jupitel_thunder', treeRow: 0, treeCol: 0, prerequisites: [{ skillId: 203, level: 1 }, { skillId: 202, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 20+i*3, castTime: 2000+i*500, cooldown: 0, effectValue: 3+i, duration: 0 })) },
    { id: 801, name: 'lord_of_vermilion', displayName: 'Lord of Vermilion', classId: 'wizard', maxLevel: 10, type: 'active', targetType: 'ground', element: 'wind', range: 450, description: 'Massive lightning AoE.', icon: 'lord_of_vermilion', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 212, level: 1 }, { skillId: 800, level: 5 }], levels: genLevels(10, i => ({ level: i+1, spCost: 60+i*4, castTime: 5000+i*500, cooldown: 5000, effectValue: 100+i*20, duration: 0 })) },
    { id: 802, name: 'meteor_storm', displayName: 'Meteor Storm', classId: 'wizard', maxLevel: 10, type: 'active', targetType: 'ground', element: 'fire', range: 450, description: 'Rain meteors over area.', icon: 'meteor_storm', treeRow: 1, treeCol: 2, prerequisites: [{ skillId: 207, level: 1 }, { skillId: 209, level: 1 }, { skillId: 205, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 20+i*4, castTime: 5000+i*1000, cooldown: 2000, effectValue: 100+i*20, duration: 0 })) },
    { id: 803, name: 'storm_gust', displayName: 'Storm Gust', classId: 'wizard', maxLevel: 10, type: 'active', targetType: 'ground', element: 'water', range: 450, description: 'Freezing blizzard AoE.', icon: 'storm_gust', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 208, level: 1 }, { skillId: 800, level: 3 }], levels: genLevels(10, i => ({ level: i+1, spCost: 60+i*6, castTime: 5000+i*500, cooldown: 5000, effectValue: 100+i*20, duration: 0 })) },
    { id: 804, name: 'earth_spike', displayName: 'Earth Spike', classId: 'wizard', maxLevel: 5, type: 'active', targetType: 'single', element: 'earth', range: 450, description: 'Earth spikes strike.', icon: 'earth_spike', treeRow: 0, treeCol: 3, prerequisites: [{ skillId: 206, level: 1 }], levels: genLevels(5, i => ({ level: i+1, spCost: 12+i*4, castTime: 1500, cooldown: 0, effectValue: i+1, duration: 0 })) },
    { id: 805, name: 'heavens_drive', displayName: "Heaven's Drive", classId: 'wizard', maxLevel: 5, type: 'active', targetType: 'ground', element: 'earth', range: 450, description: 'AoE earth spike.', icon: 'heavens_drive', treeRow: 1, treeCol: 3, prerequisites: [{ skillId: 804, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 28+i*4, castTime: 2000, cooldown: 0, effectValue: i+1, duration: 0 })) },
    { id: 806, name: 'quagmire', displayName: 'Quagmire', classId: 'wizard', maxLevel: 5, type: 'active', targetType: 'ground', element: 'earth', range: 450, description: 'Swamp that reduces AGI/DEX.', icon: 'quagmire', treeRow: 2, treeCol: 3, prerequisites: [{ skillId: 805, level: 1 }], levels: genLevels(5, i => ({ level: i+1, spCost: 5+i*5, castTime: 1000, cooldown: 0, effectValue: (i+1)*5, duration: 5000+i*2000 })) },
    { id: 807, name: 'water_ball', displayName: 'Water Ball', classId: 'wizard', maxLevel: 5, type: 'active', targetType: 'single', element: 'water', range: 450, description: 'Multi water hits. Needs water.', icon: 'water_ball', treeRow: 0, treeCol: 1, prerequisites: [{ skillId: 200, level: 1 }, { skillId: 202, level: 1 }], levels: genLevels(5, i => ({ level: i+1, spCost: 15+i*5, castTime: 2500, cooldown: 0, effectValue: 100, duration: 0 })) },
    { id: 808, name: 'ice_wall', displayName: 'Ice Wall', classId: 'wizard', maxLevel: 10, type: 'active', targetType: 'ground', element: 'water', range: 450, description: 'Create blocking ice wall.', icon: 'ice_wall', treeRow: 0, treeCol: 2, prerequisites: [{ skillId: 206, level: 1 }, { skillId: 208, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 20, castTime: 2000, cooldown: 0, effectValue: 0, duration: 4000+i*4000 })) },
    { id: 809, name: 'sight_rasher', displayName: 'Sight Rasher', classId: 'wizard', maxLevel: 10, type: 'active', targetType: 'aoe', element: 'fire', range: 0, description: 'Explode Sight for fire AoE.', icon: 'sight_rasher', treeRow: 2, treeCol: 2, prerequisites: [{ skillId: 205, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 35+i*3, castTime: 0, cooldown: 2000, effectValue: 100+i*20, duration: 0 })) },

    // === SAGE (IDs 1400-1419) ===
    { id: 1400, name: 'study', displayName: 'Study', classId: 'sage', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases Max SP and INT.', icon: 'study', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: i+1, duration: 0 })) },
    { id: 1401, name: 'cast_cancel', displayName: 'Cast Cancel', classId: 'sage', maxLevel: 5, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Cancel spell, recover SP.', icon: 'cast_cancel', treeRow: 0, treeCol: 1, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 2, castTime: 0, cooldown: 0, effectValue: (i+1)*15, duration: 0 })) },
    { id: 1402, name: 'hindsight', displayName: 'Hindsight', classId: 'sage', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Auto-cast bolts on melee.', icon: 'hindsight', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 1401, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 20+i*5, castTime: 2000, cooldown: 0, effectValue: i+1, duration: 60000+i*30000 })) },
    { id: 1403, name: 'dispell', displayName: 'Dispell', classId: 'sage', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 450, description: 'Remove all buffs from target.', icon: 'dispell', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1401, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 1, castTime: 1000, cooldown: 2000, effectValue: 60+i*8, duration: 0 })) },
    { id: 1404, name: 'magic_rod', displayName: 'Magic Rod', classId: 'sage', maxLevel: 5, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Absorb spell targeting you as SP.', icon: 'magic_rod', treeRow: 0, treeCol: 2, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 2, castTime: 0, cooldown: 500, effectValue: (i+1)*20, duration: 0 })) },

    // === HUNTER (IDs 900-919) ===
    { id: 900, name: 'blitz_beat', displayName: 'Blitz Beat', classId: 'hunter', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 800, description: 'Falcon attacks target.', icon: 'blitz_beat', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 10+i*3, castTime: 0, cooldown: 1000, effectValue: i+1, duration: 0 })) },
    { id: 901, name: 'steel_crow', displayName: 'Steel Crow', classId: 'hunter', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases falcon damage.', icon: 'steel_crow', treeRow: 1, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*6, duration: 0 })) },
    { id: 902, name: 'detect', displayName: 'Detect', classId: 'hunter', maxLevel: 4, type: 'active', targetType: 'ground', element: 'neutral', range: 600, description: 'Reveal hidden enemies.', icon: 'detect', treeRow: 0, treeCol: 2, prerequisites: [], levels: genLevels(4, i => ({ level: i+1, spCost: 8+i*2, castTime: 0, cooldown: 1000, effectValue: 0, duration: 0 })) },
    { id: 903, name: 'ankle_snare', displayName: 'Ankle Snare', classId: 'hunter', maxLevel: 5, type: 'active', targetType: 'ground', element: 'neutral', range: 600, description: 'Trap that immobilizes.', icon: 'ankle_snare', treeRow: 0, treeCol: 1, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 12, castTime: 0, cooldown: 1000, effectValue: 0, duration: 4000+i*4000 })) },
    { id: 904, name: 'land_mine', displayName: 'Land Mine', classId: 'hunter', maxLevel: 5, type: 'active', targetType: 'ground', element: 'earth', range: 600, description: 'Explosive trap with stun.', icon: 'land_mine', treeRow: 1, treeCol: 1, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 10, castTime: 0, cooldown: 1000, effectValue: 50+i*50, duration: 0 })) },
    { id: 905, name: 'remove_trap', displayName: 'Remove Trap', classId: 'hunter', maxLevel: 1, type: 'active', targetType: 'ground', element: 'neutral', range: 150, description: 'Remove a placed trap.', icon: 'remove_trap', treeRow: 2, treeCol: 1, prerequisites: [], levels: [{ level: 1, spCost: 5, castTime: 0, cooldown: 0, effectValue: 0, duration: 0 }] },
    { id: 906, name: 'shockwave_trap', displayName: 'Shockwave Trap', classId: 'hunter', maxLevel: 5, type: 'active', targetType: 'ground', element: 'neutral', range: 600, description: 'Trap that drains SP.', icon: 'shockwave_trap', treeRow: 1, treeCol: 2, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 45, castTime: 0, cooldown: 1000, effectValue: 5+i*5, duration: 0 })) },
    { id: 907, name: 'claymore_trap', displayName: 'Claymore Trap', classId: 'hunter', maxLevel: 5, type: 'active', targetType: 'ground', element: 'fire', range: 600, description: 'AoE fire explosion trap.', icon: 'claymore_trap', treeRow: 2, treeCol: 2, prerequisites: [{ skillId: 906, level: 1 }, { skillId: 904, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 15, castTime: 0, cooldown: 1000, effectValue: 100+i*40, duration: 0 })) },

    // === BARD (IDs 1500-1519) ===
    { id: 1500, name: 'music_lessons', displayName: 'Music Lessons', classId: 'bard', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases instrument ATK and songs.', icon: 'music_lessons', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*3, duration: 0 })) },
    { id: 1501, name: 'a_poem_of_bragi', displayName: 'A Poem of Bragi', classId: 'bard', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Reduce cast time for allies.', icon: 'a_poem_of_bragi', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 1500, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 20+i*5, castTime: 0, cooldown: 0, effectValue: 3+i*3, duration: 60000 })) },
    { id: 1502, name: 'assassin_cross_of_sunset', displayName: 'Assassin Cross of Sunset', classId: 'bard', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Increase ASPD for allies.', icon: 'assassin_cross_of_sunset', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1500, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 38+i*2, castTime: 0, cooldown: 0, effectValue: i+1, duration: 60000 })) },

    // === DANCER (IDs 1520-1539) ===
    { id: 1520, name: 'dance_lessons', displayName: 'Dance Lessons', classId: 'dancer', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases whip ATK and dances.', icon: 'dance_lessons', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*3, duration: 0 })) },
    { id: 1521, name: 'service_for_you', displayName: 'Service For You', classId: 'dancer', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Increase Max SP, reduce SP use.', icon: 'service_for_you', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 1520, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 40+i*5, castTime: 0, cooldown: 0, effectValue: (i+1)*3, duration: 60000 })) },
    { id: 1522, name: 'humming', displayName: 'Humming', classId: 'dancer', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Increase HIT for allies.', icon: 'humming', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1520, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 22+i*4, castTime: 0, cooldown: 0, effectValue: 2+i*2, duration: 60000 })) },

    // === PRIEST (IDs 1000-1019) ===
    { id: 1000, name: 'sanctuary', displayName: 'Sanctuary', classId: 'priest', maxLevel: 10, type: 'active', targetType: 'ground', element: 'holy', range: 450, description: 'AoE healing zone.', icon: 'sanctuary', treeRow: 0, treeCol: 0, prerequisites: [{ skillId: 400, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 15+i*3, castTime: 3000, cooldown: 0, effectValue: 100+i*100, duration: 4000+i*1000 })) },
    { id: 1001, name: 'kyrie_eleison', displayName: 'Kyrie Eleison', classId: 'priest', maxLevel: 10, type: 'active', targetType: 'single', element: 'holy', range: 450, description: 'Absorb hits barrier.', icon: 'kyrie_eleison', treeRow: 0, treeCol: 1, prerequisites: [{ skillId: 406, level: 2 }], levels: genLevels(10, i => ({ level: i+1, spCost: 20+i*2, castTime: 2000, cooldown: 0, effectValue: 12+i*2, duration: 120000 })) },
    { id: 1002, name: 'magnificat', displayName: 'Magnificat', classId: 'priest', maxLevel: 5, type: 'active', targetType: 'self', element: 'holy', range: 0, description: 'Double party SP regen.', icon: 'magnificat', treeRow: 1, treeCol: 0, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 40, castTime: 4000, cooldown: 0, effectValue: 100, duration: 30000+i*10000 })) },
    { id: 1003, name: 'gloria', displayName: 'Gloria', classId: 'priest', maxLevel: 5, type: 'active', targetType: 'self', element: 'holy', range: 0, description: 'Party LUK +30.', icon: 'gloria', treeRow: 1, treeCol: 1, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 20, castTime: 0, cooldown: 0, effectValue: 30, duration: 10000+i*5000 })) },
    { id: 1004, name: 'resurrection', displayName: 'Resurrection', classId: 'priest', maxLevel: 4, type: 'active', targetType: 'single', element: 'holy', range: 450, description: 'Revive dead players.', icon: 'resurrection', treeRow: 0, treeCol: 2, prerequisites: [{ skillId: 400, level: 4 }], levels: [
        { level: 1, spCost: 60, castTime: 6000, cooldown: 0, effectValue: 10, duration: 0 },
        { level: 2, spCost: 60, castTime: 4000, cooldown: 0, effectValue: 30, duration: 0 },
        { level: 3, spCost: 60, castTime: 2000, cooldown: 0, effectValue: 50, duration: 0 },
        { level: 4, spCost: 60, castTime: 0, cooldown: 0, effectValue: 80, duration: 0 },
    ] },
    { id: 1005, name: 'magnus_exorcismus', displayName: 'Magnus Exorcismus', classId: 'priest', maxLevel: 10, type: 'active', targetType: 'ground', element: 'holy', range: 450, description: 'Holy AoE vs Undead/Demon.', icon: 'magnus_exorcismus', treeRow: 2, treeCol: 0, prerequisites: [{ skillId: 409, level: 1 }, { skillId: 1000, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 40+i*2, castTime: 5000, cooldown: 4000, effectValue: 100+i*20, duration: 5000+i*500 })) },
    { id: 1006, name: 'turn_undead', displayName: 'Turn Undead', classId: 'priest', maxLevel: 10, type: 'active', targetType: 'single', element: 'holy', range: 450, description: 'Instant-kill Undead chance.', icon: 'turn_undead', treeRow: 2, treeCol: 1, prerequisites: [{ skillId: 1004, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 10+i*2, castTime: 1000, cooldown: 500, effectValue: i*3, duration: 0 })) },
    { id: 1007, name: 'lex_aeterna', displayName: 'Lex Aeterna', classId: 'priest', maxLevel: 1, type: 'active', targetType: 'single', element: 'neutral', range: 450, description: 'Next damage dealt to target is doubled.', icon: 'lex_aeterna', treeRow: 1, treeCol: 2, prerequisites: [], levels: [{ level: 1, spCost: 10, castTime: 0, cooldown: 3000, effectValue: 200, duration: 0 }] },

    // === MONK (IDs 1600-1619) ===
    { id: 1600, name: 'iron_fists', displayName: 'Iron Fists', classId: 'monk', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases unarmed ATK.', icon: 'iron_fists', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*3, duration: 0 })) },
    { id: 1601, name: 'summon_spirit_sphere', displayName: 'Summon Spirit Sphere', classId: 'monk', maxLevel: 5, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Summon a spirit sphere.', icon: 'summon_spirit_sphere', treeRow: 0, treeCol: 1, prerequisites: [{ skillId: 1600, level: 2 }], levels: genLevels(5, i => ({ level: i+1, spCost: 8, castTime: 1000, cooldown: 0, effectValue: i+1, duration: 600000 })) },
    { id: 1602, name: 'occult_impaction', displayName: 'Occult Impaction', classId: 'monk', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: 'Extra damage vs high DEF. Uses sphere.', icon: 'occult_impaction', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 1601, level: 5 }], levels: genLevels(5, i => ({ level: i+1, spCost: 10+i*3, castTime: 0, cooldown: 500, effectValue: 100+i*40, duration: 0 })) },
    { id: 1603, name: 'investigate', displayName: 'Investigate', classId: 'monk', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: 'DEF-scaling damage. Uses sphere.', icon: 'investigate', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1601, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 10+i*4, castTime: 500, cooldown: 500, effectValue: 150+i*50, duration: 0 })) },
    { id: 1604, name: 'finger_offensive', displayName: 'Finger Offensive', classId: 'monk', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 450, description: 'Throw all spheres at target.', icon: 'finger_offensive', treeRow: 2, treeCol: 0, prerequisites: [{ skillId: 1603, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 10+i*3, castTime: 1000, cooldown: 1000, effectValue: 150+i*50, duration: 0 })) },
    { id: 1605, name: 'asura_strike', displayName: 'Asura Strike', classId: 'monk', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: 'Consume all SP for massive damage.', icon: 'asura_strike', treeRow: 2, treeCol: 1, prerequisites: [{ skillId: 1604, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 0, castTime: 4000-i*500, cooldown: 3000, effectValue: 250+i*150, duration: 0 })) },

    // === ASSASSIN (IDs 1100-1119) ===
    { id: 1100, name: 'katar_mastery', displayName: 'Katar Mastery', classId: 'assassin', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases Katar ATK.', icon: 'katar_mastery', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*3, duration: 0 })) },
    { id: 1101, name: 'sonic_blow', displayName: 'Sonic Blow', classId: 'assassin', maxLevel: 10, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: '8 rapid katar hits.', icon: 'sonic_blow', treeRow: 0, treeCol: 1, prerequisites: [{ skillId: 1100, level: 4 }], levels: genLevels(10, i => ({ level: i+1, spCost: 16+i*2, castTime: 0, cooldown: 2000, effectValue: 50+i*50, duration: 0 })) },
    { id: 1102, name: 'grimtooth', displayName: 'Grimtooth', classId: 'assassin', maxLevel: 5, type: 'active', targetType: 'ground', element: 'neutral', range: 450, description: 'Attack from Hiding.', icon: 'grimtooth', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 1100, level: 5 }, { skillId: 503, level: 2 }], levels: genLevels(5, i => ({ level: i+1, spCost: 3, castTime: 0, cooldown: 500, effectValue: 100+i*20, duration: 0 })) },
    { id: 1103, name: 'cloaking', displayName: 'Cloaking', classId: 'assassin', maxLevel: 10, type: 'toggle', targetType: 'self', element: 'neutral', range: 0, description: 'Invisible near walls. Can move.', icon: 'cloaking', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 503, level: 2 }], levels: genLevels(10, i => ({ level: i+1, spCost: 15, castTime: 0, cooldown: 500, effectValue: i+1, duration: 0 })) },
    { id: 1104, name: 'poison_react', displayName: 'Poison React', classId: 'assassin', maxLevel: 10, type: 'active', targetType: 'self', element: 'poison', range: 0, description: 'Counter poison with auto-Envenom.', icon: 'poison_react', treeRow: 2, treeCol: 0, prerequisites: [{ skillId: 504, level: 3 }], levels: genLevels(10, i => ({ level: i+1, spCost: 25+i*5, castTime: 0, cooldown: 0, effectValue: i+1, duration: 20000+i*5000 })) },
    { id: 1105, name: 'venom_dust', displayName: 'Venom Dust', classId: 'assassin', maxLevel: 10, type: 'active', targetType: 'ground', element: 'poison', range: 450, description: 'Poison cloud on ground.', icon: 'venom_dust', treeRow: 2, treeCol: 1, prerequisites: [{ skillId: 504, level: 5 }], levels: genLevels(10, i => ({ level: i+1, spCost: 20+i*2, castTime: 0, cooldown: 2000, effectValue: 0, duration: 5000+i*5000 })) },
    { id: 1106, name: 'sonic_acceleration', displayName: 'Sonic Acceleration', classId: 'assassin', maxLevel: 1, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increase Sonic Blow damage by 50%.', icon: 'sonic_acceleration', treeRow: 0, treeCol: 2, prerequisites: [{ skillId: 1101, level: 5 }], levels: [{ level: 1, spCost: 0, castTime: 0, cooldown: 0, effectValue: 50, duration: 0 }] },

    // === ROGUE (IDs 1700-1719) ===
    { id: 1700, name: 'snatcher', displayName: 'Snatcher', classId: 'rogue', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Auto-steal on attack.', icon: 'snatcher', treeRow: 0, treeCol: 0, prerequisites: [{ skillId: 502, level: 1 }], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*5, duration: 0 })) },
    { id: 1701, name: 'back_stab', displayName: 'Back Stab', classId: 'rogue', maxLevel: 10, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: 'Attack from behind.', icon: 'back_stab', treeRow: 0, treeCol: 1, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 16, castTime: 0, cooldown: 500, effectValue: 200+i*40, duration: 0 })) },
    { id: 1702, name: 'tunnel_drive', displayName: 'Tunnel Drive', classId: 'rogue', maxLevel: 5, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Move while Hiding.', icon: 'tunnel_drive', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 503, level: 1 }], levels: genLevels(5, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*20, duration: 0 })) },
    { id: 1703, name: 'raid', displayName: 'Raid', classId: 'rogue', maxLevel: 5, type: 'active', targetType: 'aoe', element: 'neutral', range: 0, description: 'AoE from Hiding.', icon: 'raid', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1702, level: 2 }, { skillId: 1701, level: 2 }], levels: genLevels(5, i => ({ level: i+1, spCost: 20, castTime: 0, cooldown: 3000, effectValue: 120+i*20, duration: 0 })) },
    { id: 1704, name: 'intimidate', displayName: 'Intimidate', classId: 'rogue', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 150, description: 'Attack and teleport both.', icon: 'intimidate', treeRow: 2, treeCol: 1, prerequisites: [{ skillId: 1703, level: 5 }, { skillId: 1701, level: 4 }], levels: genLevels(5, i => ({ level: i+1, spCost: 13+i*2, castTime: 0, cooldown: 2000, effectValue: 150+i*20, duration: 0 })) },

    // === BLACKSMITH (IDs 1200-1219) ===
    { id: 1200, name: 'adrenaline_rush', displayName: 'Adrenaline Rush', classId: 'blacksmith', maxLevel: 5, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'ASPD boost for axes/maces.', icon: 'adrenaline_rush', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 20+i*4, castTime: 0, cooldown: 0, effectValue: 30, duration: 30000+i*30000 })) },
    { id: 1201, name: 'weapon_perfection', displayName: 'Weapon Perfection', classId: 'blacksmith', maxLevel: 5, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Full damage to all sizes.', icon: 'weapon_perfection', treeRow: 0, treeCol: 1, prerequisites: [{ skillId: 1200, level: 2 }], levels: genLevels(5, i => ({ level: i+1, spCost: 18+i*2, castTime: 0, cooldown: 0, effectValue: 100, duration: 10000+i*5000 })) },
    { id: 1202, name: 'power_thrust', displayName: 'Power Thrust', classId: 'blacksmith', maxLevel: 5, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Increase ATK. Weapon break risk.', icon: 'power_thrust', treeRow: 1, treeCol: 0, prerequisites: [{ skillId: 1200, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 15+i*3, castTime: 0, cooldown: 0, effectValue: 5+i*5, duration: 20000+i*10000 })) },
    { id: 1203, name: 'maximize_power', displayName: 'Maximize Power', classId: 'blacksmith', maxLevel: 5, type: 'toggle', targetType: 'self', element: 'neutral', range: 0, description: 'Always max weapon damage.', icon: 'maximize_power', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1202, level: 3 }], levels: genLevels(5, i => ({ level: i+1, spCost: 10-i, castTime: 0, cooldown: 0, effectValue: 100, duration: 0 })) },
    { id: 1204, name: 'weaponry_research', displayName: 'Weaponry Research', classId: 'blacksmith', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases ATK and HIT.', icon: 'weaponry_research', treeRow: 0, treeCol: 2, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*2, duration: 0 })) },
    { id: 1205, name: 'skin_tempering', displayName: 'Skin Tempering', classId: 'blacksmith', maxLevel: 5, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Fire/Neutral resistance.', icon: 'skin_tempering', treeRow: 1, treeCol: 2, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*4, duration: 0 })) },

    // === ALCHEMIST (IDs 1800-1819) ===
    { id: 1800, name: 'pharmacy', displayName: 'Pharmacy', classId: 'alchemist', maxLevel: 10, type: 'active', targetType: 'self', element: 'neutral', range: 0, description: 'Create potions.', icon: 'pharmacy', treeRow: 0, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 5, castTime: 0, cooldown: 0, effectValue: i+1, duration: 0 })) },
    { id: 1801, name: 'acid_terror', displayName: 'Acid Terror', classId: 'alchemist', maxLevel: 5, type: 'active', targetType: 'single', element: 'neutral', range: 450, description: 'Acid attack. Armor break.', icon: 'acid_terror', treeRow: 0, treeCol: 1, prerequisites: [{ skillId: 1800, level: 5 }], levels: genLevels(5, i => ({ level: i+1, spCost: 15, castTime: 1000, cooldown: 1000, effectValue: 100+i*30, duration: 0 })) },
    { id: 1802, name: 'demonstration', displayName: 'Demonstration', classId: 'alchemist', maxLevel: 5, type: 'active', targetType: 'ground', element: 'fire', range: 450, description: 'Fire AoE ground attack.', icon: 'demonstration', treeRow: 1, treeCol: 1, prerequisites: [{ skillId: 1800, level: 4 }], levels: genLevels(5, i => ({ level: i+1, spCost: 10, castTime: 1000, cooldown: 1000, effectValue: 100+i*20, duration: 5000+i*5000 })) },
    { id: 1803, name: 'summon_flora', displayName: 'Summon Flora', classId: 'alchemist', maxLevel: 5, type: 'active', targetType: 'ground', element: 'earth', range: 450, description: 'Summon plant ally.', icon: 'summon_flora', treeRow: 0, treeCol: 2, prerequisites: [], levels: genLevels(5, i => ({ level: i+1, spCost: 20, castTime: 3000, cooldown: 0, effectValue: i+1, duration: 60000+i*30000 })) },
    { id: 1804, name: 'axe_mastery', displayName: 'Axe Mastery', classId: 'alchemist', maxLevel: 10, type: 'passive', targetType: 'none', element: 'neutral', range: 0, description: 'Increases Axe ATK.', icon: 'axe_mastery', treeRow: 1, treeCol: 0, prerequisites: [], levels: genLevels(10, i => ({ level: i+1, spCost: 0, castTime: 0, cooldown: 0, effectValue: (i+1)*3, duration: 0 })) },
];
